// GENERATED by scripts/gen-types.mjs from ../schemas/*.schema.json. DO NOT EDIT.

export interface PublicContracts {
  AccuracyIndex?: AccuracyIndex;
  AccuracyReport?: AccuracyReport;
  Article?: Article;
  ArticleIndex?: ArticleIndex;
  Downloads?: Downloads;
  HistoryIndex?: HistoryIndex;
  HistoryTable?: HistoryTable;
  ListsIndex?: ListsIndex;
  ListsSeason?: ListsSeason;
  LiveIndex?: LiveIndex;
  LiveSnapshot?: LiveSnapshot;
  MatchDetail?: MatchDetail;
  MatchIndex?: MatchIndex;
  Overview?: Overview;
  PlayerDetail?: PlayerDetail;
  PlayerIndex?: PlayerIndex;
  PlayerSeasonGames?: PlayerSeasonGames;
  PredictionIndex?: PredictionIndex;
  PredictionSet?: PredictionSet;
  QualityReport?: QualityReport;
  ReleaseManifest?: ReleaseManifest;
  TeamIndex?: TeamIndex;
  TeamSeason?: TeamSeason;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "AccuracyIndex".
 */
export interface AccuracyIndex {
  baseline_model_id: string | null;
  champion_model_id: string | null;
  model_card: string;
  reports: AccuracyIndexEntry[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "AccuracyIndexEntry".
 */
export interface AccuracyIndexEntry {
  label: string;
  model_id: string;
  origin: 'prospective' | 'replay' | 'legacy_unknown';
  resource: string;
  season: number | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "AccuracyReport".
 */
export interface AccuracyReport {
  baseline_headline: MetricBlock | null;
  baseline_id: string | null;
  cohorts: CohortMetric[];
  headline: MetricBlock;
  interval: IntervalInfo;
  interval_coverage: number | null;
  interval_median_width: number | null;
  label: string;
  mean_of_rounds_mae: number | null;
  model_id: string;
  notes: string[];
  origin: 'prospective' | 'replay' | 'legacy_unknown';
  populations: Populations;
  promotion: string;
  /**
   * download key for the scored rows CSV
   */
  rows_resource: string | null;
  season: number | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "MetricBlock".
 */
export interface MetricBlock {
  bias: number | null;
  mae: number | null;
  median_ae: number | null;
  n: number;
  rmse: number | null;
  within_10: number | null;
  within_5: number | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "CohortMetric".
 */
export interface CohortMetric {
  baseline: MetricBlock | null;
  cohort: string;
  dimension: string;
  model: MetricBlock;
  sufficient: boolean;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "IntervalInfo".
 */
export interface IntervalInfo {
  available: boolean;
  calibrated: boolean;
  level: number | null;
  method: string | null;
  reason: string | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "Populations".
 */
export interface Populations {
  excluded: number;
  exclusion_reasons: {
    [k: string]: number | undefined;
  };
  intended: number;
  joined: number;
  missing: number;
  played: number;
  predicted: number;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "Article".
 */
export interface Article {
  /**
   * sanitized at build time; allowlisted tags only
   */
  html: string;
  provenance: string;
  sources: Source[];
  summary: ArticleSummary;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "Source".
 */
export interface Source {
  label: string;
  note?: string | null;
  url?: string | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ArticleSummary".
 */
export interface ArticleSummary {
  as_of: string | null;
  category: string;
  editorial_state: 'published_archive' | 'generated' | 'draft';
  excerpt: string;
  original_path: string;
  published: string | null;
  resource: string;
  scope: 'frozen' | 'live' | 'archive';
  slug: string;
  title: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ArticleIndex".
 */
export interface ArticleIndex {
  articles: ArticleSummary[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "Downloads".
 */
export interface Downloads {
  items: DownloadItem[];
  release_id: string;
  retained: RetainedRelease[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "DownloadItem".
 */
export interface DownloadItem {
  as_of: string;
  bytes: number;
  key: string;
  kind: 'csv' | 'png' | 'svg' | 'zip' | 'json' | 'md';
  label: string;
  path: string;
  rows?: number | null;
  sha256: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "RetainedRelease".
 */
export interface RetainedRelease {
  generated_at: string;
  path: string;
  release_id: string;
  snapshot_id: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "HistoryIndex".
 */
export interface HistoryIndex {
  era_summary: {
    [k: string]: number | string | null | undefined;
  }[];
  tables: HistoryIndexEntry[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "HistoryIndexEntry".
 */
export interface HistoryIndexEntry {
  category: string;
  eras: string[];
  resources: {
    [k: string]: string | undefined;
  };
  scope: 'career' | 'single_season' | 'ranking';
  title: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "HistoryTable".
 */
export interface HistoryTable {
  category: string;
  coverage_note: string;
  era: string;
  method: string;
  method_version: string;
  rows: HistoryRow[];
  scope: 'career' | 'single_season' | 'ranking';
  title: string;
  warning: string | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "HistoryRow".
 */
export interface HistoryRow {
  clubs: string[];
  coverage: number | null;
  eligible_games: number | null;
  name: string;
  observed_games: number | null;
  player_id: string | null;
  rank: number;
  seasons: string | null;
  value: number;
  value_label: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ListsIndex".
 */
export interface ListsIndex {
  resources: {
    [k: string]: string | undefined;
  };
  seasons: number[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ListsSeason".
 */
export interface ListsSeason {
  contracts: ContractRow[];
  drafts: DraftRow[];
  schools: SchoolRow[];
  season: number;
  source_note: string;
  sources: Source[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ContractRow".
 */
export interface ContractRow {
  club: string | null;
  contract_end: number | null;
  fa_category: string | null;
  notes: string | null;
  observed_at: string | null;
  player_id: string | null;
  player_name: string;
  source_type: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "DraftRow".
 */
export interface DraftRow {
  club: string | null;
  draft_round: number | null;
  event_type: string;
  grade: string | null;
  pick: number | null;
  player_id: string | null;
  player_name: string;
  recruited_from: string | null;
  season: number;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "SchoolRow".
 */
export interface SchoolRow {
  confidence: string;
  draft_year: number | null;
  pick: number | null;
  player_id: string | null;
  player_name: string;
  school: string | null;
  school_type: string | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "LiveIndex".
 */
export interface LiveIndex {
  delivery: string;
  matches: LiveIndexEntry[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "LiveIndexEntry".
 */
export interface LiveIndexEntry {
  final: boolean;
  label: string;
  last_fetched_at: string | null;
  match_id: string | null;
  resource: string;
  source_game_id: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "LiveSnapshot".
 */
export interface LiveSnapshot {
  anomalies: string[];
  away: TeamScore;
  fetched_at: string | null;
  final: boolean;
  home: TeamScore;
  match_id: string | null;
  players: LivePlayerRow[];
  quarter: string | null;
  reads: string[];
  reliable_fields: string[];
  source_game_id: string;
  status: string | null;
  timeline: {
    [k: string]: string | number | null | undefined;
  }[];
  unavailable_fields: string[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "TeamScore".
 */
export interface TeamScore {
  behinds: number | null;
  club_id: string;
  goals: number | null;
  name: string;
  score: number | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "LivePlayerRow".
 */
export interface LivePlayerRow {
  name: string;
  player_id: string;
  /**
   * reliable numeric fields only; an absent key = not reported
   */
  stats: {
    [k: string]: number | undefined;
  };
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "MatchDetail".
 */
export interface MatchDetail {
  attendance: number | null;
  away_players: BoxScoreRow[];
  home_players: BoxScoreRow[];
  /**
   * live resource keys
   */
  live_snapshots?: string[];
  quarters: QuarterScore[];
  sources: Source[];
  /**
   * stats observed at least once in this file, in canonical order
   */
  stat_columns: string[];
  summary: MatchSummary;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "BoxScoreRow".
 */
export interface BoxScoreRow {
  name: string;
  player_id: string;
  /**
   * positional values aligned to the parent's stat_columns; null = not recorded
   */
  stats: (number | null)[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "QuarterScore".
 */
export interface QuarterScore {
  away_behinds: number | null;
  away_goals: number | null;
  home_behinds: number | null;
  home_goals: number | null;
  quarter: 'q1' | 'q2' | 'q3' | 'final';
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "MatchSummary".
 */
export interface MatchSummary {
  away: TeamScore;
  date_precision: 'minute' | 'day' | 'unknown';
  home: TeamScore;
  /**
   * local wall time as sourced, 'YYYY-MM-DD HH:MM'
   */
  local_start: string | null;
  match_date: string | null;
  match_id: string;
  replay_occurrence: number;
  round_number: number | null;
  season: number;
  stage_id: string;
  stage_label: string;
  stage_order: number;
  stage_type: 'regular' | 'final' | 'other';
  status: 'scheduled' | 'in_progress' | 'complete' | 'postponed' | 'cancelled' | 'unknown';
  venue: string | null;
  /**
   * null for draws, incomplete or unknown
   */
  winner_club_id: string | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "MatchIndex".
 */
export interface MatchIndex {
  matches: MatchSummary[];
  season: number;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "Overview".
 */
export interface Overview {
  demo: boolean;
  form_highlights: LeaderRow[];
  freshness: Freshness;
  latest_articles: ArticleSummary[];
  leaders: LeaderRow[];
  model_status: ModelStatus;
  next_fixture_reason: string | null;
  next_fixture_status: 'available' | 'unavailable' | 'expired';
  prediction_highlights: PredictionRow[];
  recent_results: MatchSummary[];
  release_id: string;
  season: number;
  snapshot_id: string;
  upcoming: MatchSummary[];
  warnings: string[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "LeaderRow".
 */
export interface LeaderRow {
  name: string;
  observed_games: number;
  player_id: string;
  stat: string;
  value: number;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "Freshness".
 */
export interface Freshness {
  /**
   * source-derived label, e.g. '2026 Grand Final'
   */
  coverage_through: string | null;
  dataset_status: 'legacy_unverified' | 'verified' | 'partial' | 'demo';
  generated_at: string;
  /**
   * UTC instant if the local start time and venue zone are known
   */
  latest_completed_match_at: string | null;
  latest_completed_match_date: string | null;
  published_at: string | null;
  /**
   * null when the source does not declare it
   */
  season_active: boolean | null;
  source_checked_at: string | null;
  stale: boolean;
  stale_reason?: string | null;
  validation_state: 'PASS' | 'FAIL' | 'UNKNOWN';
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ModelStatus".
 */
export interface ModelStatus {
  forecast_status: 'available' | 'unavailable' | 'expired';
  model: ModelInfo | null;
  reason: string | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ModelInfo".
 */
export interface ModelInfo {
  description: string;
  kind: 'baseline' | 'model';
  model_id: string;
  name: string;
  promoted: boolean;
  promotion_note: string;
  trained_cutoff: string | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "PredictionRow".
 */
export interface PredictionRow {
  club_id: string;
  club_name: string;
  eligibility_basis: string;
  forecast_cutoff: string;
  generated_at: string;
  history_games: number;
  interval_high: number | null;
  interval_level: number | null;
  interval_low: number | null;
  interval_method: string | null;
  match_id: string;
  model_id: string;
  opponent_club_id: string | null;
  opponent_name: string | null;
  origin: 'prospective' | 'replay' | 'legacy_unknown';
  player_id: string;
  player_name: string;
  predicted_disposals: number;
  prediction_id: string;
  prediction_run_id: string;
  recent_mean_5: number | null;
  scheduled_at: string | null;
  scheduled_local: string | null;
  season: number;
  selection_status: 'confirmed' | 'unconfirmed';
  snapshot_id: string;
  stage_id: string;
  stage_label: string;
  venue: string | null;
  warnings: string[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "PlayerDetail".
 */
export interface PlayerDetail {
  aliases: string[];
  birth_date: string | null;
  birth_date_quality: 'source' | 'legacy_filename' | 'conflicting' | 'unknown';
  career: StatValue[];
  /**
   * source career counter, may exceed rows
   */
  career_counter_max: number | null;
  career_games: number;
  clubs: ClubRef[];
  coverage_note: string;
  debut_date: string | null;
  first_name: string | null;
  forecast: PredictionRow | null;
  height_cm: number | null;
  id: string;
  identity_status: 'canonical' | 'alias' | 'quarantined_duplicate' | 'ambiguous';
  key: string;
  last_name: string | null;
  name: string;
  seasons: SeasonLine[];
  sources: Source[];
  weight_kg: number | null;
}
/**
 * An aggregate that discloses its denominator and coverage.
 *
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "StatValue".
 */
export interface StatValue {
  coverage: number | null;
  eligible_games: number;
  mean: number | null;
  observed_games: number;
  stat: string;
  total: number | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ClubRef".
 */
export interface ClubRef {
  club_id: string;
  name: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "SeasonLine".
 */
export interface SeasonLine {
  clubs: string[];
  games: number;
  /**
   * resource key of this season's game log
   */
  games_resource: string;
  season: number;
  stats: StatValue[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "PlayerIndex".
 */
export interface PlayerIndex {
  count: number;
  players: PlayerIndexEntry[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "PlayerIndexEntry".
 */
export interface PlayerIndexEntry {
  active: boolean;
  clubs: string[];
  first_season: number | null;
  games: number;
  id: string;
  /**
   * encoded id used in resource paths
   */
  key: string;
  last_season: number | null;
  name: string;
  /**
   * lower-case diacritic-stripped search terms
   */
  search: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "PlayerSeasonGames".
 */
export interface PlayerSeasonGames {
  games: PlayerGame[];
  player_id: string;
  season: number;
  /**
   * stats observed at least once in this file, in canonical order
   */
  stat_columns: string[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "PlayerGame".
 */
export interface PlayerGame {
  career_game_counter: number | null;
  club_id: string;
  date_quality: 'fixture_verified' | 'source' | 'inferred' | 'unknown';
  match_date: string | null;
  match_id: string;
  opponent_club_id: string | null;
  opponent_name: string | null;
  result: string | null;
  stage_label: string;
  /**
   * positional values aligned to the parent's stat_columns; null = not recorded
   */
  stats: (number | null)[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "PredictionIndex".
 */
export interface PredictionIndex {
  /**
   * resource key of the current set, if any
   */
  current: string | null;
  reason: string | null;
  sets: PredictionIndexEntry[];
  status: 'available' | 'unavailable' | 'expired';
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "PredictionIndexEntry".
 */
export interface PredictionIndexEntry {
  resource: string;
  rows: number;
  season: number;
  stage_id: string;
  stage_label: string;
  status: 'available' | 'unavailable' | 'expired';
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "PredictionSet".
 */
export interface PredictionSet {
  forecast_cutoff: string | null;
  generated_at: string;
  interval: IntervalInfo;
  model: ModelInfo | null;
  omissions: OmissionSummary[];
  reason: string | null;
  rows: PredictionRow[];
  season: number;
  stage_id: string;
  stage_label: string;
  status: 'available' | 'unavailable' | 'expired';
  target_matches: MatchSummary[];
  units?: 'disposals';
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "OmissionSummary".
 */
export interface OmissionSummary {
  count: number;
  detail?: string | null;
  reason: 'unresolved_identity' | 'insufficient_history' | 'not_in_fixture' | 'retired' | 'other';
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "QualityReport".
 */
export interface QualityReport {
  dataset_status: 'legacy_unverified' | 'verified' | 'partial' | 'demo';
  issues: QualityIssue[];
  limitations: string[];
  quarantined_rows: number;
  sources: Source[];
  table_counts: {
    [k: string]: number | undefined;
  };
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "QualityIssue".
 */
export interface QualityIssue {
  count: number;
  description: string;
  rule_id: string;
  severity: 'info' | 'warning' | 'error' | 'blocking';
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ReleaseManifest".
 */
export interface ReleaseManifest {
  /**
   * 'DEMO' for demo releases, else ''
   */
  base_label: string;
  coverage: CoverageInfo;
  demo: boolean;
  forecast: ForecastInfo;
  generated_at: string;
  release_id: string;
  resources: {
    [k: string]: ResourceRef | undefined;
  };
  schema_version?: number;
  season: number;
  snapshot_id: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "CoverageInfo".
 */
export interface CoverageInfo {
  status: 'legacy_unverified' | 'verified' | 'partial' | 'demo';
  through: string | null;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ForecastInfo".
 */
export interface ForecastInfo {
  /**
   * resource key of the current prediction set
   */
  artifact: string | null;
  model_id?: string | null;
  reason: string | null;
  status: 'available' | 'unavailable' | 'expired';
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "ResourceRef".
 */
export interface ResourceRef {
  bytes: number;
  path: string;
  sha256: string;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "TeamIndex".
 */
export interface TeamIndex {
  teams: TeamIndexEntry[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "TeamIndexEntry".
 */
export interface TeamIndexEntry {
  active: boolean;
  club_id: string;
  first_season: number | null;
  last_season: number | null;
  lineage_id: string;
  name: string;
  seasons: number[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "TeamSeason".
 */
export interface TeamSeason {
  club: ClubRef;
  five_year: LadderRow[];
  fixtures: MatchSummary[];
  form: FormEntry[];
  form_window: number;
  heuristics: Heuristic[];
  ladder: LadderRow[];
  ladder_note: string;
  leaders: LeaderRow[];
  position: number | null;
  season: number;
  team_stats: StatValue[];
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "LadderRow".
 */
export interface LadderRow {
  club_id: string;
  drawn: number;
  lost: number;
  name: string;
  /**
   * null when points_against is zero
   */
  percentage: number | null;
  played: number;
  points_against: number;
  points_for: number;
  position: number;
  premiership_points: number;
  won: number;
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "FormEntry".
 */
export interface FormEntry {
  margin: number;
  match_date: string | null;
  match_id: string;
  opponent: string;
  result: 'W' | 'L' | 'D';
}
/**
 * This interface was referenced by `PublicContracts`'s JSON-Schema
 * via the `definition` "Heuristic".
 */
export interface Heuristic {
  label: string;
  method: string;
  text: string;
}

/** Resource schema key -> TypeScript type. */
export interface ResourceTypes {
  accuracy_index: AccuracyIndex;
  accuracy_report: AccuracyReport;
  article: Article;
  article_index: ArticleIndex;
  downloads: Downloads;
  history_index: HistoryIndex;
  history_table: HistoryTable;
  lists_index: ListsIndex;
  lists_season: ListsSeason;
  live_index: LiveIndex;
  live_snapshot: LiveSnapshot;
  match_detail: MatchDetail;
  match_index: MatchIndex;
  overview: Overview;
  player_detail: PlayerDetail;
  player_index: PlayerIndex;
  player_season_games: PlayerSeasonGames;
  prediction_index: PredictionIndex;
  prediction_set: PredictionSet;
  quality: QualityReport;
  release: ReleaseManifest;
  team_index: TeamIndex;
  team_season: TeamSeason;
}
export type ResourceKind = keyof ResourceTypes;
export const RESOURCE_KINDS = ["accuracy_index","accuracy_report","article","article_index","downloads","history_index","history_table","lists_index","lists_season","live_index","live_snapshot","match_detail","match_index","overview","player_detail","player_index","player_season_games","prediction_index","prediction_set","quality","release","team_index","team_season"] as const;
export const PUBLIC_SCHEMA_VERSION = 1;
