// GENERATED by scripts/gen-types.mjs from ../schemas/*.schema.json. DO NOT EDIT.
import type { ResourceTypes } from './contracts.generated';
export interface GeneratedValidator<T> {
  (data: unknown): data is T;
  errors?: Array<{ instancePath: string; message?: string; keyword: string }> | null;
}
export declare const validateAccuracyIndex: GeneratedValidator<ResourceTypes['accuracy_index']>;
export declare const validateAccuracyReport: GeneratedValidator<ResourceTypes['accuracy_report']>;
export declare const validateArticle: GeneratedValidator<ResourceTypes['article']>;
export declare const validateArticleIndex: GeneratedValidator<ResourceTypes['article_index']>;
export declare const validateDownloads: GeneratedValidator<ResourceTypes['downloads']>;
export declare const validateHistoryIndex: GeneratedValidator<ResourceTypes['history_index']>;
export declare const validateHistoryTable: GeneratedValidator<ResourceTypes['history_table']>;
export declare const validateListsIndex: GeneratedValidator<ResourceTypes['lists_index']>;
export declare const validateListsSeason: GeneratedValidator<ResourceTypes['lists_season']>;
export declare const validateLiveIndex: GeneratedValidator<ResourceTypes['live_index']>;
export declare const validateLiveSnapshot: GeneratedValidator<ResourceTypes['live_snapshot']>;
export declare const validateMatchDetail: GeneratedValidator<ResourceTypes['match_detail']>;
export declare const validateMatchIndex: GeneratedValidator<ResourceTypes['match_index']>;
export declare const validateOverview: GeneratedValidator<ResourceTypes['overview']>;
export declare const validatePlayerDetail: GeneratedValidator<ResourceTypes['player_detail']>;
export declare const validatePlayerIndex: GeneratedValidator<ResourceTypes['player_index']>;
export declare const validatePlayerSeasonGames: GeneratedValidator<ResourceTypes['player_season_games']>;
export declare const validatePredictionIndex: GeneratedValidator<ResourceTypes['prediction_index']>;
export declare const validatePredictionSet: GeneratedValidator<ResourceTypes['prediction_set']>;
export declare const validateQuality: GeneratedValidator<ResourceTypes['quality']>;
export declare const validateRelease: GeneratedValidator<ResourceTypes['release']>;
export declare const validateTeamIndex: GeneratedValidator<ResourceTypes['team_index']>;
export declare const validateTeamSeason: GeneratedValidator<ResourceTypes['team_season']>;
