// Generates TypeScript types and standalone runtime validators from ../schemas/*.schema.json.
// The schemas are generated from the Python view models (Gaffer owns them); never edit the
// generated outputs by hand. `node scripts/gen-types.mjs --check` fails if outputs are stale.
import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { compile } from 'json-schema-to-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, '..');
export const schemaDir = resolve(webRoot, process.env.SCVIA_SCHEMA_DIR ?? '../schemas');
const typesOut = join(webRoot, 'src/lib/contracts.generated.ts');
const validatorsOut = join(webRoot, 'src/lib/validators.generated.js');
const validatorsDts = join(webRoot, 'src/lib/validators.generated.d.ts');
const splitDir = join(webRoot, 'src/lib/validators');

const HEADER = '// GENERATED by scripts/gen-types.mjs from ../schemas/*.schema.json. DO NOT EDIT.\n';

export function loadSchemas() {
  const files = readdirSync(schemaDir).filter((f) => f.endsWith('.schema.json')).sort();
  if (files.length === 0) throw new Error(`no schemas in ${schemaDir}`);
  return files.map((f) => ({ key: f.replace('.schema.json', ''), schema: JSON.parse(readFileSync(join(schemaDir, f), 'utf8')) }));
}

/** Drop per-property `title`s so json-schema-to-typescript does not mint an alias per field. */
function stripTitles(node, keep) {
  if (Array.isArray(node)) return node.map((n) => stripTitles(n, false));
  if (node && typeof node === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(node)) {
      if (k === 'title' && !keep) continue;
      if (k === '$defs') {
        out[k] = Object.fromEntries(Object.entries(v).map(([dk, dv]) => [dk, stripTitles(dv, true)]));
      } else if (k === 'properties') {
        out[k] = Object.fromEntries(Object.entries(v).map(([pk, pv]) => [pk, stripTitles(pv, false)]));
      } else {
        out[k] = stripTitles(v, false);
      }
    }
    return out;
  }
  return node;
}

export function mergedSchema(schemas) {
  const defs = {};
  const roots = {};
  for (const { key, schema } of schemas) {
    for (const [name, def] of Object.entries(schema.$defs ?? {})) {
      const text = JSON.stringify(def);
      if (defs[name] && JSON.stringify(defs[name]) !== text) {
        throw new Error(`conflicting $defs.${name} across schemas (${key})`);
      }
      defs[name] = def;
    }
    const { $defs: _d, $id: _i, $schema: _s, 'x-public-schema-version': _v, ...root } = schema;
    if (!root.title) throw new Error(`schema ${key} has no title`);
    if (defs[root.title]) throw new Error(`root title ${root.title} collides with a $def`);
    roots[root.title] = root;
    defs[root.title] = root;
  }
  const merged = {
    title: 'PublicContracts',
    type: 'object',
    additionalProperties: false,
    properties: Object.fromEntries(Object.keys(roots).map((t) => [t, { $ref: `#/$defs/${t}` }])),
    $defs: defs,
  };
  return { merged: stripTitles(merged, true), roots };
}

function pascal(key) {
  return key.split('_').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
}

export async function generate() {
  const schemas = loadSchemas();
  const { merged } = mergedSchema(schemas);
  let ts = await compile(merged, 'PublicContracts', {
    bannerComment: HEADER.trim(),
    additionalProperties: false,
    unreachableDefinitions: true,
    strictIndexSignatures: true,
    format: true,
    style: { singleQuote: true },
  });
  const keyMap = schemas.map(({ key, schema }) => `  ${key}: ${schema.title};`).join('\n');
  const versions = [...new Set(schemas.map((s) => s.schema['x-public-schema-version']))];
  if (versions.length !== 1) throw new Error(`mixed x-public-schema-version: ${versions}`);
  ts += `\n/** Resource schema key -> TypeScript type. */\nexport interface ResourceTypes {\n${keyMap}\n}\nexport type ResourceKind = keyof ResourceTypes;\nexport const RESOURCE_KINDS = ${JSON.stringify(schemas.map((s) => s.key))} as const;\nexport const PUBLIC_SCHEMA_VERSION = ${versions[0]};\n`;

  const ajv = new Ajv2020({ strict: true, allErrors: false, code: { source: true, esm: true, lines: false }, allowUnionTypes: true });
  addFormats(ajv, ['date', 'date-time']);
  ajv.addKeyword('x-public-schema-version');
  const refs = {};
  for (const { key, schema } of schemas) {
    ajv.addSchema(schema);
    refs[`validate${pascal(key)}`] = schema.$id;
  }
  let code = standaloneCode(ajv, refs).replace(/^"use strict";/, '');
  // ajv's standalone output uses require() for format functions even in ESM mode.
  code = code.replace(/require\("ajv-formats\/dist\/formats"\)\.fullFormats/g, '__ajvFullFormats');
  if (code.includes('require(')) throw new Error('unexpected require() left in standalone validators');
  const js = HEADER + '/* eslint-disable */\n// @ts-nocheck\nimport { fullFormats as __ajvFullFormats } from "ajv-formats/dist/formats.js";\n' + code;
  const dts = HEADER + "import type { ResourceTypes } from './contracts.generated';\nexport interface GeneratedValidator<T> {\n  (data: unknown): data is T;\n  errors?: Array<{ instancePath: string; message?: string; keyword: string }> | null;\n}\n" +
    schemas.map(({ key }) => `export declare const validate${pascal(key)}: GeneratedValidator<ResourceTypes['${key}']>;`).join('\n') + '\n';
  // Per-resource modules so each browser island only ships the validators it uses.
  const split = {};
  for (const { key, schema } of schemas) {
    let one = standaloneCode(ajv, { validate: schema.$id }).replace(/^"use strict";/, '');
    one = one.replace(/require\("ajv-formats\/dist\/formats"\)\.fullFormats/g, '__ajvFullFormats');
    if (one.includes('require(')) throw new Error('unexpected require() in split validator');
    const needsFormats = one.includes('__ajvFullFormats');
    split[`${key}.generated.js`] = HEADER + '/* eslint-disable */\n// @ts-nocheck\n' + (needsFormats ? 'import { fullFormats as __ajvFullFormats } from "ajv-formats/dist/formats.js";\n' : '') + one;
  }
  split['index.generated.ts'] = HEADER + "import type { ResourceKind, ResourceTypes } from '../contracts.generated';\nimport type { GeneratedValidator } from '../validators.generated.js';\n\n/** Lazy per-resource validator loaders (code-split by the bundler). */\nexport const VALIDATOR_LOADERS: { [K in ResourceKind]: () => Promise<GeneratedValidator<ResourceTypes[K]>> } = {\n" +
    schemas.map(({ key }) => `  ${key}: () => import('./${key}.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['${key}']>),`).join('\n') + '\n};\n';
  return { ts, js, dts, split };
}

async function main() {
  const check = process.argv.includes('--check');
  const { ts, js, dts, split } = await generate();
  mkdirSync(splitDir, { recursive: true });
  const outputs = [[typesOut, ts], [validatorsOut, js], [validatorsDts, dts], ...Object.entries(split).map(([f, c]) => [join(splitDir, f), c])];
  if (check) {
    const stale = outputs.filter(([p, c]) => !existsSync(p) || readFileSync(p, 'utf8') !== c).map(([p]) => p);
    if (stale.length) {
      console.error(`generated contracts are stale; run npm run gen:types:\n${stale.join('\n')}`);
      process.exit(1);
    }
    console.log('generated contracts up to date');
    return;
  }
  for (const [p, c] of outputs) writeFileSync(p, c);
  console.log(`wrote ${outputs.map(([p]) => p).join(', ')}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
