// GENERATED by scripts/gen-types.mjs from ../schemas/*.schema.json. DO NOT EDIT.
import type { ResourceKind, ResourceTypes } from '../contracts.generated';
import type { GeneratedValidator } from '../validators.generated.js';

/** Lazy per-resource validator loaders (code-split by the bundler). */
export const VALIDATOR_LOADERS: { [K in ResourceKind]: () => Promise<GeneratedValidator<ResourceTypes[K]>> } = {
  accuracy_index: () => import('./accuracy_index.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['accuracy_index']>),
  accuracy_report: () => import('./accuracy_report.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['accuracy_report']>),
  article: () => import('./article.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['article']>),
  article_index: () => import('./article_index.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['article_index']>),
  downloads: () => import('./downloads.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['downloads']>),
  history_index: () => import('./history_index.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['history_index']>),
  history_table: () => import('./history_table.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['history_table']>),
  lists_index: () => import('./lists_index.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['lists_index']>),
  lists_season: () => import('./lists_season.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['lists_season']>),
  live_index: () => import('./live_index.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['live_index']>),
  live_snapshot: () => import('./live_snapshot.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['live_snapshot']>),
  match_detail: () => import('./match_detail.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['match_detail']>),
  match_index: () => import('./match_index.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['match_index']>),
  overview: () => import('./overview.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['overview']>),
  player_detail: () => import('./player_detail.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['player_detail']>),
  player_index: () => import('./player_index.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['player_index']>),
  player_season_games: () => import('./player_season_games.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['player_season_games']>),
  prediction_index: () => import('./prediction_index.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['prediction_index']>),
  prediction_set: () => import('./prediction_set.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['prediction_set']>),
  quality: () => import('./quality.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['quality']>),
  release: () => import('./release.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['release']>),
  team_index: () => import('./team_index.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['team_index']>),
  team_season: () => import('./team_season.generated.js').then((m) => m.validate as GeneratedValidator<ResourceTypes['team_season']>),
};
