"""Legacy CSV corpus -> immutable, coverage-aware canonical snapshot.

``import_legacy`` reads every file under ``<source_root>/data`` (plus the root biography
export), accounts for each one as imported / ignored-with-reason / quarantined, maps the
legacy columns to canonical tables (``domain.schemas.TABLES``) and writes a content-hashed
snapshot through ``SnapshotBuilder``. Nothing is silently dropped: every legacy row is
either imported or quarantined with its original cells and a reason. Imported legacy data
is always ``DatasetStatus.LEGACY_UNVERIFIED``.

Determinism: tables are sorted by key, IDs are content/identity derived and no wall-clock
value enters any row, so identical inputs give the identical snapshot ID.
"""

from __future__ import annotations

import builtins
import csv
import hashlib
import io
import json
import os
import re
import time
from collections import Counter, defaultdict
from collections.abc import Callable, Iterable, Mapping
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from typing import Any

from supercoach_via.domain import ids, season
from supercoach_via.domain.schemas import (
    LEGACY_PLAYER_COLUMN_MAP,
    PLAYER_STAT_COLUMNS,
    TABLES,
    DatasetStatus,
    DatePrecision,
    DateQuality,
    IdentityStatus,
    MatchStatus,
    Origin,
    Provenance,
    Severity,
    StageType,
)
from supercoach_via.settings import RunContext
from supercoach_via.storage.snapshots import SnapshotBuilder, SnapshotCandidate

IMPORTER_VERSION = "legacy-import-v1"
REPO_CONFIG_DIR = Path(__file__).resolve().parents[3] / "config"
EVIDENCE_REL = "docs/rewrite/evidence/refresh-sources.json"
ROOT_BIOS = "all_time_top_100.csv"

LEGACY_PLAYER_HEADER: tuple[str, ...] = (
    "team", "year", "games_played", "opponent", "round", "result", "jersey_num",
    "kicks", "marks", "handballs", "disposals", "goals", "behinds", "hit_outs", "tackles",
    "rebound_50s", "inside_50s", "clearances", "clangers", "free_kicks_for",
    "free_kicks_against", "brownlow_votes", "contested_possessions",
    "uncontested_possessions", "contested_marks", "marks_inside_50", "one_percenters",
    "bounces", "goal_assist", "percentage_of_game_played", "date",
)  # fmt: skip
MATCH_HEADER: tuple[str, ...] = (
    "round_num", "venue", "date", "year", "attendance",
    "team_1_team_name", "team_1_q1_goals", "team_1_q1_behinds", "team_1_q2_goals",
    "team_1_q2_behinds", "team_1_q3_goals", "team_1_q3_behinds", "team_1_final_goals",
    "team_1_final_behinds",
    "team_2_team_name", "team_2_q1_goals", "team_2_q1_behinds", "team_2_q2_goals",
    "team_2_q2_behinds", "team_2_q3_goals", "team_2_q3_behinds", "team_2_final_goals",
    "team_2_final_behinds",
)  # fmt: skip
_QUARTERS = ("q1", "q2", "q3", "final")
_CANON_OF_LEGACY = {c: LEGACY_PLAYER_COLUMN_MAP.get(c, c) for c in LEGACY_PLAYER_HEADER}
_LEGACY_STATS = LEGACY_PLAYER_HEADER[7:30]
assert tuple(_CANON_OF_LEGACY[c] for c in _LEGACY_STATS) == PLAYER_STAT_COLUMNS

#: family -> (mandatory, description). Absent optional families are reported, not errors.
FAMILIES: dict[str, bool] = {
    "matches": True,
    "player_performance": True,
    "player_personal": False,
    "lineups": False,
    "drafts_national": False,
    "drafts_rookie": False,
    "drafts_draftguru": False,
    "draft_schools": False,
    "contracts": False,
    "conceded_stats": False,
    "live_state": False,
    "live_players": False,
    "legacy_predictions": False,
    "legacy_backtest": False,
    "model_cache": False,
    "rank_scores": False,
    "rank_yearly": False,
    "top100_bios": False,
    "era_outputs": False,
    "player_status": False,
    "identity_evidence": False,
    "placeholder": False,
    "unknown": False,
}
IGNORED_REASONS: dict[str, str] = {
    "conceded_stats": "derived output regenerated by analytics (known legacy column-rotation defect)",
    "legacy_backtest": "derived legacy backtest output; replay is regenerated by ml.evaluate",
    "model_cache": "legacy Optuna tuning cache; not data (model bundles are rebuilt)",
    "era_outputs": "derived output regenerated by analytics",
    "player_status": "derived output regenerated by analytics",
    "placeholder": "empty directory placeholder (.gitkeep); no data",
}


class LegacyImportError(RuntimeError):
    """The legacy corpus cannot be imported (missing mandatory family, bad config)."""


# ---------------------------------------------------------------------------
# Result objects
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DatasetCandidate:
    """An imported, not-yet-promoted snapshot plus its JSON-able import report."""

    candidate: SnapshotCandidate
    report: dict[str, Any]
    data_root: Path

    @property
    def snapshot_id(self) -> str:
        return self.candidate.manifest.snapshot_id

    @property
    def manifest_path(self) -> Path:
        return self.candidate.manifest_path


def write_import_report(candidate: DatasetCandidate, path: Path) -> None:
    from supercoach_via.storage.snapshots import atomic_write_bytes

    atomic_write_bytes(path, json.dumps(candidate.report, indent=1, sort_keys=True, default=str).encode())


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def _h(*parts: object, n: int = 24) -> str:
    return hashlib.sha256("\x1f".join(str(p) for p in parts).encode()).hexdigest()[:n]


def classify(rel: str) -> str:
    """Map a repo-relative path to its legacy file family."""
    name = rel.rsplit("/", 1)[-1]
    if rel == ROOT_BIOS:
        return "top100_bios"
    if name == ".gitkeep":
        return "placeholder"
    if rel == EVIDENCE_REL:
        return "identity_evidence"
    if re.fullmatch(r"data/matches/matches_\d{4}\.csv", rel):
        return "matches"
    if rel.startswith("data/player_data/") and rel.count("/") == 2:
        if name.endswith(ids.PERFORMANCE_SUFFIX):
            return "player_performance"
        if name.endswith(ids.PERSONAL_SUFFIX):
            return "player_personal"
    if re.fullmatch(r"data/lineups/team_lineups_[a-z_]+\.csv", rel):
        return "lineups"
    fixed = {
        "data/drafts/afl_draft_history.csv": "drafts_national",
        "data/drafts/afl_rookie_draft_history.csv": "drafts_rookie",
        "data/drafts/draftguru_enrichment.csv": "drafts_draftguru",
        "data/drafts/afl_draft_schools.csv": "draft_schools",
        "data/top100/all_time_top_100.csv": "rank_scores",
        "data/player_status.csv": "player_status",
        "data/prediction/optuna_best_params.json": "model_cache",
    }
    if rel in fixed:
        return fixed[rel]
    if re.fullmatch(r"data/contracts/[^/]+\.csv", rel):
        return "contracts"
    if re.fullmatch(r"data/conceded_stats/[^/]+\.csv", rel):
        return "conceded_stats"
    if re.fullmatch(r"data/live_snapshots/[^/]+\.json", rel):
        return "live_state"
    if re.fullmatch(r"data/live_snapshots/[^/]+_players\.csv", rel):
        return "live_players"
    if rel.startswith("data/prediction/backtest/"):
        return "legacy_backtest"
    if re.fullmatch(r"data/prediction/(oldModelData/)?(next_[a-z0-9_]+|prediction_vs_actual_[a-z0-9_]+)\.csv", rel):
        return "legacy_predictions"
    if re.fullmatch(r"data/top100/yearly/year_\d{4}\.csv", rel):
        return "rank_yearly"
    if re.fullmatch(r"data/era_[a-z_]+\.(csv|json)", rel):
        return "era_outputs"
    return "unknown"


@dataclass
class FileRecord:
    path: str
    family: str
    bytes: int
    sha256: str
    data: builtins.bytes
    disposition: str = "imported"
    reason: str | None = None
    rows_read: int | None = None
    rows_imported: int | None = None
    rows_quarantined: int | None = None

    def count(self, read: int, imported: int, quarantined: int) -> None:
        self.rows_read = (self.rows_read or 0) + read
        self.rows_imported = (self.rows_imported or 0) + imported
        self.rows_quarantined = (self.rows_quarantined or 0) + quarantined

    def as_report(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "family": self.family,
            "bytes": self.bytes,
            "sha256": self.sha256,
            "disposition": self.disposition,
            "reason": self.reason,
            "rows_read": self.rows_read,
            "rows_imported": self.rows_imported,
            "rows_quarantined": self.rows_quarantined,
        }


def _read_file(path: Path, rel: str) -> FileRecord:
    data = path.read_bytes()
    return FileRecord(rel, classify(rel), len(data), hashlib.sha256(data).hexdigest(), data)


def _inventory(source_root: Path) -> list[FileRecord]:
    data_dir = source_root / "data"
    if not data_dir.is_dir():
        raise LegacyImportError(f"no data/ directory under {source_root}")
    targets: list[tuple[Path, str]] = []
    for dirpath, dirnames, filenames in os.walk(data_dir):
        dirnames.sort()
        for fn in sorted(filenames):
            p = Path(dirpath) / fn
            targets.append((p, p.relative_to(source_root).as_posix()))
    for extra in (ROOT_BIOS, EVIDENCE_REL):
        if (source_root / extra).is_file():
            targets.append((source_root / extra, extra))
    with ThreadPoolExecutor(max_workers=8) as pool:
        records = list(pool.map(lambda t: _read_file(*t), targets))
    return sorted(records, key=lambda r: r.path)


class IssueSink:
    """Collects quality_issues rows with deterministic IDs."""

    def __init__(self) -> None:
        self.rows: dict[str, dict[str, Any]] = {}

    def add(
        self,
        rule_id: str,
        severity: Severity,
        explanation: str,
        *,
        table: str | None = None,
        row_key: str | None = None,
        source_path: str | None = None,
        season: int | None = None,
        remediation: str | None = None,
        status: str = "open",
        acceptance_basis: str | None = None,
    ) -> None:
        issue_id = f"qi:{_h(rule_id, table, row_key, source_path, explanation)}"
        self.rows[issue_id] = {
            "issue_id": issue_id,
            "severity": severity.value,
            "status": status,
            "table_name": table,
            "row_key": row_key,
            "source_path": source_path,
            "rule_id": rule_id,
            "explanation": explanation,
            "remediation": remediation,
            "acceptance_basis": acceptance_basis,
            "season": season,
        }


class Quarantine:
    def __init__(self) -> None:
        self.rows: dict[str, dict[str, Any]] = {}

    def add(
        self,
        table: str,
        reason: str,
        raw: Mapping[str, Any],
        rec: FileRecord,
        source_row: int | None,
        *,
        season: int | None = None,
        candidates: Any = None,
        discriminator: str = "",
    ) -> None:
        qid = f"q:{_h(table, rec.path, source_row, reason, discriminator)}"
        self.rows[qid] = {
            "quarantine_id": qid,
            "table_name": table,
            "reason": reason,
            "candidates": None if candidates is None else json.dumps(candidates, sort_keys=True, default=str),
            "raw": json.dumps(raw, ensure_ascii=False, sort_keys=True),
            "season": season,
            "provenance": Provenance.LEGACY_IMPORT.value,
            "source_path": rec.path,
            "source_sha256": rec.sha256,
            "source_row": source_row,
        }


def _src(rec: FileRecord, row: int | None) -> dict[str, Any]:
    return {
        "provenance": Provenance.LEGACY_IMPORT.value,
        "source_path": rec.path,
        "source_sha256": rec.sha256,
        "source_row": row,
    }


def _csv_rows(rec: FileRecord) -> tuple[list[str], list[list[str]]]:
    text = rec.data.decode("utf-8-sig")
    reader = csv.reader(io.StringIO(text))
    header = next(reader, [])
    return header, [r for r in reader if r]


def _int(v: str | None) -> int | None:
    if v is None:
        return None
    v = v.strip()
    if re.fullmatch(r"-?\d+(\.0+)?", v):
        return int(v.split(".", 1)[0])
    return None


def _float(v: str | None) -> float | None:
    try:
        return float(v) if v not in (None, "") else None
    except ValueError:
        return None


def _date(v: str) -> date | None:
    try:
        return date.fromisoformat(v[:10]) if re.fullmatch(r"\d{4}-\d{2}-\d{2}", v[:10]) else None
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Import state shared across families
# ---------------------------------------------------------------------------


@dataclass
class MatchRef:
    match_id: str
    season: int
    stage_id: str
    home: str
    away: str
    match_date: date | None
    local_start: str | None
    occurrence: int


@dataclass
class State:
    clubs: ids.ClubRegistry
    venues: ids.VenueRegistry
    issues: IssueSink = field(default_factory=IssueSink)
    quarantine: Quarantine = field(default_factory=Quarantine)
    matches: dict[str, MatchRef] = field(default_factory=dict)
    # (season, stage_id, club, opponent) -> matches sorted by occurrence
    link_index: dict[tuple[int, str, str, str], list[MatchRef]] = field(default_factory=dict)
    # (season, stage_id, club) -> matches (lineups have no opponent)
    club_stage_index: dict[tuple[int, str, str], list[MatchRef]] = field(default_factory=dict)
    players: dict[str, dict[str, Any]] = field(default_factory=dict)
    player_names: dict[str, set[str]] = field(default_factory=dict)  # player_id -> normalized names
    # built from player_games: (match_id, club) -> name -> [pid]; (season, club) -> name -> {pid}
    match_names: dict[tuple[str, str], dict[str, list[str]]] = field(default_factory=dict)
    club_season_names: dict[tuple[int, str], dict[str, set[str]]] = field(default_factory=dict)
    season_players: dict[int, set[str]] = field(default_factory=dict)
    first_season: dict[str, int] = field(default_factory=dict)
    _name_index: dict[str, set[str]] | None = None

    def name_index(self) -> dict[str, set[str]]:
        """normalized name -> canonical player ids (built once, after player_games)."""
        if self._name_index is None:
            idx: dict[str, set[str]] = {}
            for pid, names in self.player_names.items():
                if self.players[pid]["identity_status"] == IdentityStatus.CANONICAL.value:
                    for nm in names:
                        idx.setdefault(nm, set()).add(pid)
            self._name_index = idx
        return self._name_index

    accounting: dict[str, Any] = field(default_factory=dict)


def _club(state: State, name: str, season_: int, rec: FileRecord) -> str | None:
    before = set(state.clubs.created)
    cid = state.clubs.resolve_or_create(name, season_)
    for new in set(state.clubs.created) - before:
        state.issues.add(
            "club_auto_created",
            Severity.WARNING,
            f"club name {name!r} is absent from team_aliases.csv; created entity {new!r} "
            "with its own lineage (no merger inferred)",
            table="clubs",
            row_key=new,
            source_path=rec.path,
            season=season_,
            remediation="add the name to config/team_aliases.csv with a verified interval/lineage",
        )
    return cid


# ---------------------------------------------------------------------------
# Matches
# ---------------------------------------------------------------------------


_SCORE_TOKEN = re.compile(r"^\d+\.\d+\.\d+$")
OpponentEvidence = Callable[[int, str, str], str | None]


def opponent_evidence(perf: list[FileRecord]) -> OpponentEvidence:
    """Lookup (season, stage_id, team name) -> the opponent name iff player rows agree both ways.

    Unanimous means: every row of ``team`` in that season/stage names the same opponent X,
    and every row of X in that season/stage names ``team``. Used only to recover the club
    of a malformed legacy match row (never scores). Scans raw bytes; called rarely.
    """
    ncells = len(LEGACY_PLAYER_HEADER)

    def opponents(season_: int, stage_id: str, team: str) -> list[str]:
        needle = f"\n{team},{season_},".encode()
        found: list[str] = []
        for rec in perf:
            data = rec.data
            start = data.find(needle)
            while start != -1:
                end = data.find(b"\n", start + 1)
                cells = data[start + 1 : end if end != -1 else None].decode("utf-8").rstrip("\r").split(",")
                if len(cells) == ncells and season.parse_stage_cached(cells[4]).stage_id == stage_id:
                    found.append(cells[3])
                start = data.find(needle, start + 1)
        return found

    def lookup(season_: int, stage_id: str, team: str) -> str | None:
        forward = set(opponents(season_, stage_id, team))
        if len(forward) != 1:
            return None
        opp = next(iter(forward))
        back = set(opponents(season_, stage_id, opp))
        return opp if back == {team} else None

    return lookup


def _import_matches(
    state: State, records: list[FileRecord], evidence: OpponentEvidence | None = None
) -> list[dict[str, Any]]:
    staged: list[dict[str, Any]] = []
    for rec in records:
        header, rows = _csv_rows(rec)
        if tuple(header) != MATCH_HEADER:
            rec.disposition, rec.reason = "quarantined", "unexpected match header"
            for i, r in enumerate(rows, start=1):
                state.quarantine.add("matches", "unexpected_header", {"cells": r, "header": header}, rec, i)
            rec.count(len(rows), 0, len(rows))
            continue
        imported = quarantined = 0
        for i, cells in enumerate(rows, start=1):
            raw: dict[str, Any] = dict(zip(MATCH_HEADER, cells, strict=False))
            yr = _int(raw.get("year"))
            reason = None
            if len(cells) != len(MATCH_HEADER):
                reason, raw = "malformed_column_count", {"cells": cells}
            elif yr is None:
                reason = "malformed_value"
            score_cells = [raw[f"team_{t}_{q}_{k}"] for t in (1, 2) for q in _QUARTERS for k in ("goals", "behinds")]
            if reason is None and any(c.strip() and _int(c) is None for c in score_cells):
                reason = "malformed_value"
            home = away = None
            malformed_opp: str | None = None
            if reason is None and yr is not None:
                home = _club(state, raw["team_1_team_name"], yr, rec)
                if _SCORE_TOKEN.match(raw["team_2_team_name"].strip()) and evidence is not None and home:
                    # extra-time final: legacy scraper wrote a score into team_2's name cell
                    malformed_opp = evidence(yr, season.parse_stage(raw["round_num"]).stage_id, raw["team_1_team_name"])
                    away = _club(state, malformed_opp, yr, rec) if malformed_opp else None
                else:
                    away = _club(state, raw["team_2_team_name"], yr, rec)
                if home is None or away is None or home == away:
                    reason = "unresolved_club"
                    malformed_opp = None
            if reason is not None or yr is None or home is None or away is None:
                state.quarantine.add("matches", reason or "malformed_value", raw, rec, i, season=yr)
                state.issues.add(
                    f"match_{reason}",
                    Severity.ERROR,
                    f"match row quarantined: {reason}",
                    table="matches",
                    row_key=f"{rec.path}:{i}",
                    source_path=rec.path,
                    season=yr,
                    remediation="repair from source (refresh --repair-season)",
                )
                quarantined += 1
                continue
            stage = season.parse_stage(raw["round_num"])
            if not stage.recognized:
                state.issues.add(
                    "stage_unrecognized",
                    Severity.ERROR,
                    f"unrecognized stage token {stage.label!r} preserved as {stage.stage_id} (stage_type=other)",
                    table="matches",
                    row_key=f"{rec.path}:{i}",
                    source_path=rec.path,
                    season=yr,
                    remediation="map the token in domain.season before time-sensitive use",
                )
            dt_raw = raw["date"].strip()
            local_start: str | None = None
            match_date = _date(dt_raw)
            if match_date is not None and re.fullmatch(r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}", dt_raw):
                local_start, precision = dt_raw, DatePrecision.MINUTE
            elif match_date is not None:
                precision = DatePrecision.DAY
            else:
                precision = DatePrecision.UNKNOWN
                state.issues.add(
                    "match_date_unparseable",
                    Severity.WARNING,
                    f"match date {dt_raw!r} unparseable",
                    table="matches",
                    row_key=f"{rec.path}:{i}",
                    source_path=rec.path,
                    season=yr,
                )
            if match_date is not None and match_date.year != yr:
                state.issues.add(
                    "match_date_outside_season",
                    Severity.WARNING,
                    f"match date {match_date} outside season {yr}",
                    table="matches",
                    row_key=f"{rec.path}:{i}",
                    source_path=rec.path,
                    season=yr,
                )
            scores = {
                f"{side}_{q}_{k}": None if malformed_opp else _int(raw[f"team_{t}_{q}_{k}"])
                for t, side in ((1, "home"), (2, "away"))
                for q in _QUARTERS
                for k in ("goals", "behinds")
            }
            if malformed_opp:
                state.quarantine.add("matches", "source_row_malformed_evidence", raw, rec, i, season=yr)
            att = raw["attendance"].strip()
            attendance = _int(att) if att not in ("", "N/A") else None
            staged.append(
                {
                    "season": yr,
                    "stage": stage,
                    "home": home,
                    "away": away,
                    "home_source_name": raw["team_1_team_name"],
                    "away_source_name": malformed_opp or raw["team_2_team_name"],
                    "malformed_raw": dict(raw) if malformed_opp else None,
                    "venue_source_name": raw["venue"] or None,
                    "local_start": local_start,
                    "match_date": match_date,
                    "precision": precision,
                    "attendance": attendance,
                    "scores": scores,
                    "rec": rec,
                    "row": i,
                    "tiebreak": len(staged),
                }
            )
            imported += 1
        rec.count(len(rows), imported, quarantined)
        if quarantined and not imported:
            rec.disposition = "quarantined"

    # completion status: all score cells present -> complete; all blank -> fixture
    completed_dates = [
        s["match_date"]
        for s in staged
        if s["match_date"] is not None
        and all(s["scores"][f"{side}_final_{k}"] is not None for side in ("home", "away") for k in ("goals", "behinds"))
    ]
    latest_complete = max(completed_dates) if completed_dates else None

    by_season: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for s in staged:
        by_season[s["season"]].append(s)
    out: list[dict[str, Any]] = []
    observed_venues: dict[str, set[str]] = defaultdict(set)
    for yr in sorted(by_season):
        group = by_season[yr]
        occ = season.replay_occurrences(
            [(s["stage"].stage_id, s["home"], s["away"], s["match_date"]) for s in group],
            [s["tiebreak"] for s in group],
        )
        stage_dates: dict[str, list[date | None]] = defaultdict(list)
        for s in group:
            stage_dates[s["stage"].stage_id].append(s["match_date"])
        orders = season.stage_orders(stage_dates)
        for s, o in zip(group, occ, strict=True):
            stage = s["stage"]
            rec = s["rec"]
            mid = season.make_match_id(yr, stage.stage_id, s["home"], s["away"], o)
            sc = s["scores"]
            finals_present = all(
                sc[f"{side}_final_{k}"] is not None for side in ("home", "away") for k in ("goals", "behinds")
            )
            any_present = any(v is not None for v in sc.values())
            if s["malformed_raw"] is not None:
                status = MatchStatus.UNKNOWN
                state.issues.add(
                    "source_row_malformed",
                    Severity.ERROR,
                    "legacy row has a score in team_2_team_name (extra-time final); team 2 cells are "
                    f"shifted so ALL scores are null; away club {s['away']!r} taken from unanimous two-way "
                    "player-row opponent evidence; raw row: "
                    + json.dumps(s["malformed_raw"], ensure_ascii=False, sort_keys=True),
                    table="matches",
                    row_key=mid,
                    source_path=rec.path,
                    season=yr,
                    remediation="re-fetch the match from source (refresh --repair-season)",
                )
            elif finals_present:
                status = MatchStatus.COMPLETE
            elif (
                not any_present
                and s["match_date"] is not None
                and latest_complete is not None
                and s["match_date"] > latest_complete
            ):
                status = MatchStatus.SCHEDULED
            else:
                status = MatchStatus.UNKNOWN
                state.issues.add(
                    "match_scores_missing" if not any_present else "match_scores_partial",
                    Severity.WARNING if not any_present else Severity.ERROR,
                    "match has no scores and is not later than the latest completed match"
                    if not any_present
                    else "match has partial scores; status unknown",
                    table="matches",
                    row_key=mid,
                    source_path=rec.path,
                    season=yr,
                )
            if o > 0:
                prev = next(
                    x
                    for x, xo in zip(group, occ, strict=True)
                    if xo == o - 1
                    and x["stage"].stage_id == stage.stage_id
                    and {x["home"], x["away"]} == {s["home"], s["away"]}
                )
                ps = prev["scores"]
                drawn = (
                    ps["home_final_goals"] is not None
                    and ps["away_final_goals"] is not None
                    and 6 * ps["home_final_goals"] + (ps["home_final_behinds"] or 0)
                    == 6 * ps["away_final_goals"] + (ps["away_final_behinds"] or 0)
                )
                state.issues.add(
                    "replay_after_draw" if drawn else "repeat_meeting_same_stage",
                    Severity.INFO,
                    f"occurrence {o} of {stage.stage_id} between {s['home']} and {s['away']}"
                    + (" follows a drawn match (replay)" if drawn else " without a preceding draw"),
                    table="matches",
                    row_key=mid,
                    source_path=rec.path,
                    season=yr,
                )
            venue_id = state.venues.resolve(s["venue_source_name"]) if s["venue_source_name"] else None
            if s["venue_source_name"] and venue_id is None:
                state.issues.add(
                    "venue_unmapped",
                    Severity.WARNING,
                    f"venue {s['venue_source_name']!r} absent from venue_aliases.csv",
                    table="matches",
                    row_key=mid,
                    source_path=rec.path,
                    season=yr,
                )
            if venue_id is not None:
                observed_venues[venue_id].add(s["venue_source_name"])

            def pts(side: str, _sc: dict[str, int | None] = sc) -> int | None:
                g, b = _sc[f"{side}_final_goals"], _sc[f"{side}_final_behinds"]
                return None if g is None or b is None else 6 * g + b

            row = {
                "match_id": mid,
                "season": yr,
                "stage_label": stage.label,
                "stage_type": stage.stage_type.value,
                "round_number": stage.round_number,
                "stage_order": orders[stage.stage_id],
                "stage_id": stage.stage_id,
                "replay_occurrence": o,
                "home_club_id": s["home"],
                "away_club_id": s["away"],
                "home_source_name": s["home_source_name"],
                "away_source_name": s["away_source_name"],
                "venue_id": venue_id,
                "venue_source_name": s["venue_source_name"],
                "local_start": s["local_start"],
                "match_date": s["match_date"],
                "date_precision": s["precision"].value,
                "status": status.value,
                "attendance": s["attendance"],
                **sc,
                "home_score": pts("home"),
                "away_score": pts("away"),
                **_src(rec, s["row"]),
            }
            out.append(row)
            ref = MatchRef(mid, yr, stage.stage_id, s["home"], s["away"], s["match_date"], s["local_start"], o)
            state.matches[mid] = ref
            state.link_index.setdefault((yr, stage.stage_id, s["home"], s["away"]), []).append(ref)
            state.link_index.setdefault((yr, stage.stage_id, s["away"], s["home"]), []).append(ref)
            state.club_stage_index.setdefault((yr, stage.stage_id, s["home"]), []).append(ref)
            state.club_stage_index.setdefault((yr, stage.stage_id, s["away"]), []).append(ref)
    for lst in (*state.link_index.values(), *state.club_stage_index.values()):
        lst.sort(key=lambda m: (m.occurrence, m.match_id))
    state.accounting["venues_observed"] = {k: sorted(v) for k, v in observed_venues.items()}
    return out


# ---------------------------------------------------------------------------
# Players (identity registry)
# ---------------------------------------------------------------------------


def _load_evidence(records: Mapping[str, FileRecord]) -> dict[str, str]:
    """Legacy path -> verified source URL from the refresh reconciliation evidence."""
    rec = records.get(EVIDENCE_REL)
    if rec is None:
        return {}
    data = json.loads(rec.data)
    out: dict[str, str] = {}
    for p in data.get("players", []):
        if p.get("status") == "checked" and p.get("path") and p.get("source"):
            out[p["path"]] = p["source"]
    rec.count(len(data.get("players", [])), len(out), 0)
    rec.rows_imported, rec.rows_quarantined = len(data.get("players", [])), 0
    return out


def _import_players(
    state: State, perf: list[FileRecord], personal: list[FileRecord], evidence: dict[str, str]
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    personal_by_slug = {r.path.rsplit("/", 1)[-1][: -len(ids.PERSONAL_SUFFIX)]: r for r in personal}
    perf_by_slug = {ids.slug_from_filename(r.path.rsplit("/", 1)[-1]): r for r in perf}
    alias_by_slug = {a.slug: a for a in ids.VERIFIED_SOURCE_ALIASES}
    dup_by_slug = {d.duplicate_slug: d for d in ids.KNOWN_DUPLICATES}
    canon_urls: dict[str, list[str]] = defaultdict(list)
    for d in ids.KNOWN_DUPLICATES:
        canon_urls[d.canonical_slug].append(d.source_url)
    rows: list[dict[str, Any]] = []
    aliases: list[dict[str, Any]] = []
    for slug in sorted(set(perf_by_slug) | set(personal_by_slug)):
        pid = ids.player_id_for_slug(slug)
        prec = perf_by_slug.get(slug)
        drec = personal_by_slug.get(slug)
        first = last = born = debut = height = weight = None
        if drec is not None:
            header, prow = _csv_rows(drec)
            if prow and len(prow[0]) == len(header):
                pd_ = dict(zip(header, prow[0], strict=True))
                first = (pd_.get("first_name") or "").strip() or None
                last = (pd_.get("last_name") or "").strip() or None
                born, debut = pd_.get("born_date"), pd_.get("debut_date")
                height, weight = pd_.get("height"), pd_.get("weight")
                for extra_i, extra in enumerate(prow[1:], start=2):
                    state.quarantine.add("players", "extra_personal_details_row", {"cells": extra}, drec, extra_i)
                drec.count(len(prow), 1, len(prow) - 1)
            else:
                drec.disposition, drec.reason = "quarantined", "malformed personal-details file"
                state.quarantine.add("players", "malformed_personal_details", {"header": header, "rows": prow}, drec, 1)
                drec.count(max(len(prow), 1), 0, max(len(prow), 1))
        birth, bq, bissue = ids.resolve_birth_date(born, slug)
        if (bissue and bissue != "birth_date_from_filename") or (bissue and drec is not None):
            state.issues.add(
                bissue,
                Severity.INFO if bissue != "birth_date_conflicts_filename" else Severity.WARNING,
                f"birth date quality {bq.value} for {slug}",
                table="players",
                row_key=pid,
                source_path=drec.path if drec else prec.path if prec else None,
            )
        alias = alias_by_slug.get(slug)
        legacy_display = " ".join(x for x in (first, last) if x) or None
        if alias is not None:
            display = alias.source_name
        elif legacy_display:
            display = legacy_display
        else:
            parts = slug.split("_")
            display = " ".join(p.replace("-", " ").title() for p in (parts[1], parts[0])) if len(parts) >= 3 else slug
            state.issues.add(
                "display_name_from_slug",
                Severity.WARNING,
                f"no personal-details name for {slug}; display name derived from slug",
                table="players",
                row_key=pid,
                source_path=prec.path if prec else None,
            )
        dup = dup_by_slug.get(slug)
        urls = sorted(
            {u for u in (evidence.get(prec.path) if prec else None, alias.source_url if alias else None) if u}
            | set(canon_urls.get(slug, []))
        )
        status = IdentityStatus.CANONICAL
        canonical = None
        if dup is not None:
            if dup.canonical_slug in perf_by_slug:
                status, canonical = IdentityStatus.QUARANTINED_DUPLICATE, ids.player_id_for_slug(dup.canonical_slug)
            else:
                state.issues.add(
                    "duplicate_canonical_missing",
                    Severity.ERROR,
                    f"registry duplicate {slug} has no canonical file {dup.canonical_slug}",
                    table="players",
                    row_key=pid,
                )
        rows.append(
            {
                "player_id": pid,
                "legacy_slug": slug,
                "display_name": display,
                "first_name": first,
                "last_name": last,
                "birth_date": birth,
                "birth_date_quality": bq.value,
                "debut_date": ids._parse_ddmmyyyy(debut) if debut else None,
                "height_cm": ids.parse_measure(height),
                "weight_kg": ids.parse_measure(weight),
                "identity_status": status.value,
                "canonical_player_id": canonical,
                "source_urls": json.dumps(urls) if urls else None,
                "details_source_path": drec.path if drec else None,
                "details_source_sha256": drec.sha256 if drec else None,
                **(_src(prec, None) if prec else _src(drec, None) if drec else {}),
            }
        )
        names = {ids.normalize_name(display)}
        if legacy_display:
            names.add(ids.normalize_name(legacy_display))
        if alias is not None:
            aliases.append(
                {
                    "player_id": pid,
                    "alias": alias.source_name,
                    "alias_kind": "source_name",
                    "evidence": "verified multi-part source surname (refresh 2026-09-24)",
                    "source_url": alias.source_url,
                }
            )
            if legacy_display and legacy_display != alias.source_name:
                aliases.append(
                    {
                        "player_id": pid,
                        "alias": legacy_display,
                        "alias_kind": "display_variant",
                        "evidence": "legacy personal-details split of the source surname",
                        "source_url": alias.source_url,
                    }
                )
        if dup is not None and canonical is not None:
            aliases.append(
                {
                    "player_id": canonical,
                    "alias": slug,
                    "alias_kind": "legacy_slug",
                    "evidence": dup.reason,
                    "source_url": dup.source_url,
                }
            )
            if legacy_display:
                aliases.append(
                    {
                        "player_id": canonical,
                        "alias": legacy_display,
                        "alias_kind": "display_variant",
                        "evidence": f"display name on quarantined duplicate {slug}",
                        "source_url": dup.source_url,
                    }
                )
        state.player_names[pid] = names
        state.players[pid] = rows[-1]
    for a in aliases:
        if a["alias_kind"] == "display_variant" and a["player_id"] in state.player_names:
            state.player_names[a["player_id"]].add(ids.normalize_name(a["alias"]))
    # duplicate aliases (same alias text) collapse deterministically
    uniq = {(a["player_id"], a["alias"]): a for a in aliases}
    return rows, [uniq[k] for k in sorted(uniq)]


# ---------------------------------------------------------------------------
# Player games (bulk parse via pyarrow)
# ---------------------------------------------------------------------------

_INT_RE = r"^\d+(\.0+)?$"
_FLOAT_RE = r"^\d+(\.\d+)?$"


def _import_player_games(state: State, perf: list[FileRecord]) -> Any:
    import pyarrow as pa
    import pyarrow.compute as pc
    import pyarrow.csv as pacsv

    header_line = ",".join(LEGACY_PLAYER_HEADER)
    ncomma = len(LEGACY_PLAYER_HEADER) - 1
    lines: list[str] = []
    raw_lines: list[str] = []
    line_meta: list[tuple[int, int]] = []  # (file index, source row)
    acc_read: Counter[int | None] = Counter()
    acc_imp: Counter[int | None] = Counter()
    acc_q: Counter[int | None] = Counter()
    per_file = [[0, 0, 0] for _ in perf]  # read, imported, quarantined
    dup_slugs = {d.duplicate_slug for d in ids.KNOWN_DUPLICATES}

    def season_of(cells: list[str]) -> int | None:
        return _int(cells[1]) if len(cells) > 1 else None

    for fi, rec in enumerate(perf):
        text = rec.data.decode("utf-8-sig")
        flines = text.split("\n")
        header = flines[0].rstrip("\r") if flines else ""
        body = [ln.rstrip("\r") for ln in flines[1:]]
        if header != header_line:
            rec.disposition, rec.reason = "quarantined", "unexpected performance header"
            for i, ln in enumerate((b for b in body if b), start=1):
                state.quarantine.add("player_games", "unexpected_header", {"line": ln, "header": header}, rec, i)
                per_file[fi][0] += 1
                per_file[fi][2] += 1
                acc_read[None] += 1
                acc_q[None] += 1
            continue
        row_no = 0
        for ln in body:
            if not ln:
                continue
            row_no += 1
            per_file[fi][0] += 1
            if ln.count(",") != ncomma or '"' in ln:
                cells = ln.split(",")
                sn = season_of(cells)
                state.quarantine.add("player_games", "malformed_column_count", {"line": ln}, rec, row_no, season=sn)
                per_file[fi][2] += 1
                acc_read[sn] += 1
                acc_q[sn] += 1
                continue
            lines.append(f"{fi},{row_no},{ln}")
            raw_lines.append(ln)
            line_meta.append((fi, row_no))

    names = ["fidx", "srow", *LEGACY_PLAYER_HEADER]
    blob = "\n".join(lines).encode()
    del lines
    if blob:
        table = pacsv.read_csv(
            io.BytesIO(blob),
            read_options=pacsv.ReadOptions(column_names=names, use_threads=True, block_size=1 << 24),
            parse_options=pacsv.ParseOptions(quote_char=False, escape_char=False, newlines_in_values=False),
            convert_options=pacsv.ConvertOptions(
                column_types={n: (pa.int32() if n in ("fidx", "srow") else pa.string()) for n in names},
                strings_can_be_null=False,
                quoted_strings_can_be_null=False,
            ),
        )
    else:
        table = pa.table({n: pa.array([], pa.int32() if n in ("fidx", "srow") else pa.string()) for n in names})
    del blob
    n = table.num_rows
    empty = pa.scalar(None, pa.string())

    def blank_to_null(col: Any) -> Any:
        return pc.if_else(pc.equal(col, ""), empty, col)

    bad = pa.array([False] * n)
    typed: dict[str, Any] = {}
    for legacy_name in _LEGACY_STATS:
        col = table[legacy_name]
        canon = _CANON_OF_LEGACY[legacy_name]
        pattern = _FLOAT_RE if canon == "time_on_ground_pct" else _INT_RE
        ok = pc.or_(pc.equal(col, ""), pc.match_substring_regex(col, pattern))
        bad = pc.or_(bad, pc.invert(ok))
        clean = pc.if_else(ok, blank_to_null(col), empty)
        if canon == "time_on_ground_pct":
            typed[canon] = pc.cast(clean, pa.float64())
        else:
            typed[canon] = pc.cast(pc.replace_substring_regex(clean, r"\.0+$", ""), pa.int32())
    year_ok = pc.match_substring_regex(table["year"], r"^\d{4}$")
    bad = pc.or_(bad, pc.invert(year_ok))
    gp = table["games_played"]
    gp_ok = pc.or_(pc.equal(gp, ""), pc.match_substring_regex(gp, r"^\d+[↑↓]?$"))
    bad = pc.or_(bad, pc.invert(gp_ok))
    counter_str = pc.replace_substring_regex(pc.if_else(gp_ok, blank_to_null(gp), empty), r"[↑↓]$", "")
    counter = pc.cast(counter_str, pa.int32())
    jersey = table["jersey_num"]
    jersey_ok = pc.or_(pc.equal(jersey, ""), pc.match_substring_regex(jersey, _INT_RE))
    bad = pc.or_(bad, pc.invert(jersey_ok))
    jersey_int = pc.cast(
        pc.replace_substring_regex(pc.if_else(jersey_ok, blank_to_null(jersey), empty), r"\.0+$", ""), pa.int32()
    )
    date_str = table["date"]
    date_ok = pc.match_substring_regex(date_str, r"^\d{4}-\d{2}-\d{2}$")
    row_dates = pc.cast(
        pc.strptime(pc.if_else(date_ok, date_str, empty), format="%Y-%m-%d", unit="s", error_is_null=True),
        pa.date32(),
    )

    bad_l: list[bool] = bad.to_pylist()
    year_l: list[int | None] = [
        int(y) if ok else None for y, ok in zip(table["year"].to_pylist(), year_ok.to_pylist(), strict=True)
    ]
    team_l: list[str] = table["team"].to_pylist()
    opp_l: list[str] = table["opponent"].to_pylist()
    round_l: list[str] = table["round"].to_pylist()
    date_l: list[date | None] = row_dates.to_pylist()

    slugs = [ids.slug_from_filename(r.path.rsplit("/", 1)[-1]) for r in perf]
    pids = [ids.player_id_for_slug(s) for s in slugs]
    # link
    match_l: list[str | None] = [None] * n
    club_l: list[str | None] = [None] * n
    oppid_l: list[str | None] = [None] * n
    stage_l: list[str] = [""] * n
    method_l: list[str] = [""] * n
    dq_l: list[str] = [""] * n
    reason_l: list[str | None] = [None] * n
    cand_l: dict[int, Any] = {}
    seen_key_count: Counter[tuple[int, int, str, str, str]] = Counter()
    fidx_l = [m[0] for m in line_meta]
    srow_l = [m[1] for m in line_meta]
    for i in range(n):
        fi = fidx_l[i]
        yr = year_l[i]
        if bad_l[i] or yr is None:
            reason_l[i] = "malformed_value"
            continue
        rec = perf[fi]
        club = _club(state, team_l[i], yr, rec)
        opp = _club(state, opp_l[i], yr, rec)
        if club is None or opp is None:
            reason_l[i] = "unresolved_club"
            cand_l[i] = {"team": team_l[i], "opponent": opp_l[i]}
            continue
        club_l[i], oppid_l[i] = club, opp
        stage = season.parse_stage_cached(round_l[i])
        stage_l[i] = stage.stage_id
        cands = state.link_index.get((yr, stage.stage_id, club, opp))
        if not cands:
            reason_l[i] = "unlinked_no_match"
            cand_l[i] = sorted(
                m.match_id
                for k, v in state.link_index.items()
                if k[0] == yr and k[2] == club and k[3] == opp
                for m in v
            )
            continue
        key = (fi, yr, stage.stage_id, club, opp)
        k = seen_key_count[key]
        seen_key_count[key] += 1
        chosen: MatchRef | None = None
        if len(cands) == 1:
            chosen, method = cands[0], "key"
        else:
            same_day = [m for m in cands if m.match_date is not None and m.match_date == date_l[i]]
            if len(same_day) == 1:
                chosen, method = same_day[0], "date_tiebreak"
            elif k < len(cands):
                chosen, method = cands[k], "row_order"
            else:
                method = ""
        if chosen is None:
            reason_l[i] = "ambiguous_match"
            cand_l[i] = [m.match_id for m in cands]
            continue
        match_l[i] = chosen.match_id
        method_l[i] = method
        dq_l[i] = season.row_date_quality(date_l[i], chosen.match_date, yr).value

    # dedupe (match, player, club): keep fixture-verified first, then earliest row
    groups: dict[tuple[str, str, str], list[int]] = defaultdict(list)
    for i in range(n):
        if reason_l[i] is None and match_l[i] is not None and club_l[i] is not None:
            groups[(match_l[i], pids[fidx_l[i]], club_l[i])].append(i)  # type: ignore[index]
    keep = [False] * n
    for members in groups.values():
        members.sort(key=lambda j: (dq_l[j] != DateQuality.FIXTURE_VERIFIED.value, srow_l[j]))
        keep[members[0]] = True
        for j in members[1:]:
            reason_l[j] = "duplicate_player_game"
            cand_l[j] = {"kept_source_row": srow_l[members[0]], "match_id": match_l[j]}

    # duplicate identities: quarantine, compare with canonical rows
    canon_rows: dict[tuple[str, str], int] = {}
    for i in range(n):
        if keep[i]:
            canon_rows[(pids[fidx_l[i]], match_l[i])] = i  # type: ignore[index]
    dup_canon = {
        ids.player_id_for_slug(d.duplicate_slug): ids.player_id_for_slug(d.canonical_slug) for d in ids.KNOWN_DUPLICATES
    }
    compare_cols = [c for c in LEGACY_PLAYER_HEADER if c not in ("date",)]
    for i in range(n):
        slug = slugs[fidx_l[i]]
        if (
            slug not in dup_slugs
            or state.players.get(pids[fidx_l[i]], {}).get("identity_status")
            != IdentityStatus.QUARANTINED_DUPLICATE.value
        ):
            continue
        canonical_pid = dup_canon[pids[fidx_l[i]]]
        mid = match_l[i]
        was_kept = keep[i]
        keep[i] = False
        reason_l[i] = "duplicate_identity"
        cand_l[i] = {"canonical_player_id": canonical_pid, "match_id": mid}
        cj = canon_rows.get((canonical_pid, mid)) if mid else None
        rec = perf[fidx_l[i]]
        if cj is None:
            state.issues.add(
                "duplicate_identity_unmatched_row",
                Severity.WARNING,
                f"duplicate-identity row {slug}:{srow_l[i]} has no canonical row for match {mid}",
                table="player_games",
                row_key=f"{pids[fidx_l[i]]}|{mid}",
                source_path=rec.path,
                season=year_l[i],
            )
            continue
        a = dict(zip(LEGACY_PLAYER_HEADER, raw_lines[i].split(","), strict=True))
        b = dict(zip(LEGACY_PLAYER_HEADER, raw_lines[cj].split(","), strict=True))
        diffs = {c: (a[c], b[c]) for c in compare_cols if _norm_cell(a[c]) != _norm_cell(b[c])}
        if diffs:
            state.issues.add(
                "duplicate_identity_cell_diff",
                Severity.WARNING,
                "duplicate vs canonical differing cells (duplicate, canonical): "
                + json.dumps(diffs, ensure_ascii=False, sort_keys=True),
                table="player_games",
                row_key=f"{canonical_pid}|{mid}",
                source_path=rec.path,
                season=year_l[i],
                remediation="canonical row retained; duplicate cells preserved in quarantine",
            )
        _ = was_kept

    # quarantine + accounting
    for i in range(n):
        fi = fidx_l[i]
        yr = year_l[i]
        acc_read[yr] += 1
        if keep[i]:
            acc_imp[yr] += 1
            per_file[fi][1] += 1
            continue
        acc_q[yr] += 1
        per_file[fi][2] += 1
        reason = reason_l[i] or "unlinked_no_match"
        state.quarantine.add(
            "player_games",
            reason,
            dict(zip(LEGACY_PLAYER_HEADER, raw_lines[i].split(","), strict=True)),
            perf[fi],
            srow_l[i],
            season=yr,
            candidates=cand_l.get(i),
        )
    for fi, rec in enumerate(perf):
        r, imp, q = per_file[fi]
        rec.count(r, imp, q)
        if slugs[fi] in dup_slugs and imp == 0 and r:
            rec.disposition, rec.reason = "quarantined", "duplicate legacy identity (see DATA_REFRESH.md)"

    # aggregated issues (row-level would be noise): row-order links, inferred/source dates
    agg: Counter[tuple[str, int]] = Counter()
    for i in range(n):
        if keep[i]:
            if method_l[i] == "row_order":
                agg[("player_game_linked_by_row_order", year_l[i] or 0)] += 1
            if dq_l[i] != DateQuality.FIXTURE_VERIFIED.value:
                agg[(f"player_date_{dq_l[i]}", year_l[i] or 0)] += 1
    for (rule, yr), cnt in sorted(agg.items()):
        state.issues.add(
            rule,
            Severity.INFO,
            f"{cnt} imported player-game rows in {yr}: {rule.replace('_', ' ')}",
            table="player_games",
            row_key=f"season:{yr}",
            season=yr,
        )
    for (q_reason, yr), cnt in sorted(
        Counter((reason_l[i], year_l[i]) for i in range(n) if not keep[i]).items(), key=str
    ):
        state.issues.add(
            f"player_game_quarantined_{q_reason}",
            Severity.INFO if q_reason == "duplicate_identity" else Severity.WARNING,
            f"{cnt} player-game rows quarantined in {yr}: {q_reason}",
            table="player_games",
            row_key=f"season:{yr}",
            season=yr,
        )

    # build canonical table
    idx = pa.array([i for i in range(n) if keep[i]], pa.int64())
    kept_i = idx.to_pylist()
    rev = [f"rev:{hashlib.sha256(raw_lines[i].encode()).hexdigest()[:32]}" for i in kept_i]
    cols: dict[str, Any] = {
        "match_id": pa.array([match_l[i] for i in kept_i], pa.string()),
        "player_id": pa.array([pids[fidx_l[i]] for i in kept_i], pa.string()),
        "club_id": pa.array([club_l[i] for i in kept_i], pa.string()),
        "season": pa.array([year_l[i] for i in kept_i], pa.int32()),
        "opponent_club_id": pa.array([oppid_l[i] for i in kept_i], pa.string()),
        "stage_label": pc.take(table["round"], idx),
        "stage_id": pa.array([stage_l[i] for i in kept_i], pa.string()),
        "club_source_name": pc.take(table["team"], idx),
        "opponent_source_name": pc.take(table["opponent"], idx),
        "link_method": pa.array([method_l[i] for i in kept_i], pa.string()),
        "match_date": pc.take(row_dates, idx),
        "date_quality": pa.array([dq_l[i] for i in kept_i], pa.string()),
        "career_game_counter": pc.take(counter, idx),
        "career_game_counter_token": pc.take(blank_to_null(gp), idx),
        "result": pc.take(blank_to_null(table["result"]), idx),
        "jersey_number": pc.take(jersey_int, idx),
        **{c: pc.take(typed[c], idx) for c in PLAYER_STAT_COLUMNS},
        "available_at": pa.nulls(len(kept_i), pa.timestamp("us", tz="UTC")),
        "revision_id": pa.array(rev, pa.string()),
        "provenance": pa.array([Provenance.LEGACY_IMPORT.value] * len(kept_i), pa.string()),
        "source_path": pa.array([perf[fidx_l[i]].path for i in kept_i], pa.string()),
        "source_sha256": pa.array([perf[fidx_l[i]].sha256 for i in kept_i], pa.string()),
        "source_row": pa.array([srow_l[i] for i in kept_i], pa.int64()),
    }
    schema = TABLES["player_games"].arrow_schema()
    out = pa.table([cols[f.name].cast(f.type) for f in schema], schema=schema)

    # name indexes for lineups / predictions / drafts
    for i in kept_i:
        pid = pids[fidx_l[i]]
        yr = year_l[i]
        club = club_l[i]
        mid = match_l[i]
        assert yr is not None and club is not None and mid is not None
        for nm in state.player_names.get(pid, ()):
            state.match_names.setdefault((mid, club), {}).setdefault(nm, [])
            if pid not in state.match_names[(mid, club)][nm]:
                state.match_names[(mid, club)][nm].append(pid)
            state.club_season_names.setdefault((yr, club), {}).setdefault(nm, set()).add(pid)
        state.season_players.setdefault(yr, set()).add(pid)
        if yr < state.first_season.get(pid, 10_000):
            state.first_season[pid] = yr
    state.accounting["player_games"] = {
        "read": sum(acc_read.values()),
        "imported": sum(acc_imp.values()),
        "quarantined": sum(acc_q.values()),
        "by_season": {
            str(k): {"read": acc_read[k], "imported": acc_imp[k], "quarantined": acc_q[k]}
            for k in sorted(acc_read, key=lambda x: (x is None, x or 0))
        },
        "link_methods": dict(sorted(Counter(method_l[i] for i in kept_i).items())),
        "date_quality": dict(sorted(Counter(dq_l[i] for i in kept_i).items())),
    }
    return out


def _norm_cell(v: str) -> str:
    v = v.strip()
    return v[:-2] if v.endswith(".0") else v


# ---------------------------------------------------------------------------
# Lineups
# ---------------------------------------------------------------------------


def _first_last(name: str) -> tuple[str, str] | None:
    parts = name.split(" ")
    return (parts[0], parts[-1]) if len(parts) >= 2 else None


_LINEUP_COLS = (
    "match_id",
    "club_id",
    "player_id",
    "season",
    "confidence",
    "name_token",
    "resolution",
    "source_path",
    "source_sha256",
    "source_row",
)


def _import_lineups(state: State, records: list[FileRecord]) -> Any:
    """Resolve lineup name tokens to identities; returns an Arrow table (columnar: ~700k rows).

    Pass 1: exact normalized name among the players with a player_games row for that
    match+club (a set of k identical tokens resolves only if exactly k such players).
    Pass 2 (unresolved only): first + last name word unique among that match's
    still-unclaimed participants (multi-part surnames the legacy slug split), then a
    unique club-season name. Anything else is quarantined with candidates.
    """
    import pyarrow as pa

    out: dict[tuple[str, str, str], tuple[Any, ...]] = {}
    acc = Counter[str]()
    for rec in records:
        header, rows = _csv_rows(rec)
        if header != ["year", "date", "round_num", "team_name", "players"]:
            rec.disposition, rec.reason = "quarantined", "unexpected lineup header"
            for i, r in enumerate(rows, start=1):
                state.quarantine.add("lineups", "unexpected_header", {"cells": r, "header": header}, rec, i)
            rec.count(len(rows), 0, len(rows))
            acc["rows_read"] += len(rows)
            acc["rows_quarantined"] += len(rows)
            continue
        imported = quarantined = 0
        for i, cells in enumerate(rows, start=1):
            acc["rows_read"] += 1
            raw = dict(zip(header, cells, strict=False))
            yr = _int(raw.get("year"))
            tokens = [t.strip() for t in (raw.get("players") or "").split(";") if t.strip()]
            club = _club(state, raw.get("team_name", ""), yr, rec) if yr is not None and len(cells) == 5 else None
            match: MatchRef | None = None
            cands: list[MatchRef] = []
            if club is not None and yr is not None:
                stage = season.parse_stage_cached(raw["round_num"])
                cands = state.club_stage_index.get((yr, stage.stage_id, club), [])
                if len(cands) == 1:
                    match = cands[0]
                else:
                    exact = [m for m in cands if m.local_start == raw["date"].strip()]
                    if len(exact) != 1:
                        d = _date(raw["date"].strip())
                        exact = [m for m in cands if m.match_date is not None and m.match_date == d]
                    match = exact[0] if len(exact) == 1 else None
            if match is None or club is None or yr is None:
                state.quarantine.add(
                    "lineups", "lineup_row_unlinked", raw, rec, i, season=yr, candidates=[m.match_id for m in cands]
                )
                quarantined += 1
                acc["rows_quarantined"] += 1
                acc["tokens_read"] += len(tokens)
                acc["tokens_quarantined"] += len(tokens)
                continue
            imported += 1
            acc["rows_linked"] += 1
            by_name = state.match_names.get((match.match_id, club), {})
            season_names = state.club_season_names.get((yr, club), {})
            norm = [ids.normalize_name(t) for t in tokens]
            counts = Counter(norm)
            assigned: list[tuple[str, str] | None] = [None] * len(tokens)
            used_nm: Counter[str] = Counter()
            claimed: set[str] = set()
            for k, nm in enumerate(norm):  # pass 1: exact name within match participation
                pids = by_name.get(nm, [])
                if pids and len(pids) == counts[nm]:
                    pid = sorted(pids)[used_nm[nm]]
                    used_nm[nm] += 1
                    assigned[k] = (pid, "match_participation")
                    claimed.add(pid)
            participants: dict[str, set[tuple[str, str]]] = {}
            for nm, pids in by_name.items():
                fl = _first_last(nm)
                for pid in pids:
                    if fl:
                        participants.setdefault(pid, set()).add(fl)
            for k, nm in enumerate(norm):  # pass 2: fallbacks for unresolved tokens only
                if assigned[k] is not None:
                    continue
                fl = _first_last(nm)
                hits = sorted(p for p, keys in participants.items() if p not in claimed and fl in keys) if fl else []
                if len(hits) == 1 and counts[nm] == 1:
                    assigned[k] = (hits[0], "match_first_last_word")
                    claimed.add(hits[0])
                elif not by_name.get(nm) and len(season_names.get(nm, ())) == 1 and counts[nm] == 1:
                    pid = next(iter(season_names[nm]))
                    if pid not in claimed:
                        assigned[k] = (pid, "club_season")
                        claimed.add(pid)
            for k, t in enumerate(tokens):
                acc["tokens_read"] += 1
                got = assigned[k]
                key = (match.match_id, club, got[0]) if got else None
                if got is None or key is None or key in out:
                    state.quarantine.add(
                        "lineups",
                        "lineup_token_unresolved" if got is None else "lineup_token_duplicate",
                        {"token": t, "row": raw},
                        rec,
                        i,
                        season=yr,
                        candidates={
                            "match": sorted(by_name.get(norm[k], [])),
                            "club_season": sorted(season_names.get(norm[k], ())),
                        },
                        discriminator=f"{t}#{k}",
                    )
                    acc["tokens_quarantined"] += 1
                    continue
                acc["tokens_resolved"] += 1
                acc[f"resolution:{got[1]}"] += 1
                conf = "high" if got[1] == "match_participation" else "medium"
                out[key] = (match.match_id, club, got[0], yr, conf, t, got[1], rec.path, rec.sha256, i)
        rec.count(len(rows), imported, quarantined)
    for key_ in (
        "rows_read",
        "rows_linked",
        "rows_quarantined",
        "tokens_read",
        "tokens_resolved",
        "tokens_quarantined",
    ):
        acc.setdefault(key_, 0)
    acc_d: dict[str, Any] = dict(sorted(acc.items()))
    acc_d["token_resolution_rate"] = (
        round(acc["tokens_resolved"] / acc["tokens_read"], 6) if acc["tokens_read"] else None
    )
    state.accounting["lineups"] = acc_d
    keys = sorted(out)
    cols = {name: [out[k][j] for k in keys] for j, name in enumerate(_LINEUP_COLS)}
    del out
    nrows = len(keys)
    cols.update(
        role=["played"] * nrows,
        announced_at=[None] * nrows,
        provenance=[Provenance.LEGACY_IMPORT.value] * nrows,
    )
    schema = TABLES["lineups"].arrow_schema()
    return pa.Table.from_pydict({f.name: cols[f.name] for f in schema}, schema=schema)


# ---------------------------------------------------------------------------
# Name resolution for non-fact families
# ---------------------------------------------------------------------------


def _resolve_name(
    state: State,
    name: str,
    *,
    season_: int | None,
    club: str | None = None,
    reversed_order: bool = False,
    first_season_window: tuple[int, int] | None = None,
) -> str | None:
    """Unambiguous identity mapping or None. Never guesses between candidates."""
    variants = {ids.normalize_name(name)}
    if reversed_order:
        parts = ids.normalize_name(name).split(" ")
        if len(parts) >= 2:
            variants = {" ".join(parts[1:] + parts[:1]), " ".join(parts[-1:] + parts[:-1])}
    cands: set[str] = set()
    if club is not None and season_ is not None:
        names = state.club_season_names.get((season_, club), {})
        for v in variants:
            cands |= names.get(v, set())
    elif first_season_window is not None:
        lo, hi = first_season_window
        index = state.name_index()
        for v in variants:
            for pid in index.get(v, ()):
                fs = state.first_season.get(pid)
                if fs is not None and lo <= fs <= hi:
                    cands.add(pid)
    elif season_ is not None:
        index = state.name_index()
        active = state.season_players.get(season_, set())
        for v in variants:
            cands |= index.get(v, set()) & active
    return next(iter(cands)) if len(cands) == 1 else None


def _draft_club(state: State, name: str, year: int, rec: FileRecord) -> str | None:
    if not name.strip():
        return None
    # a draft held late in year Y serves season Y+1
    return state.clubs.resolve(name, year + 1) or state.clubs.resolve(name, year) or _club(state, name, year + 1, rec)


def _import_drafts(
    state: State, recs: Mapping[str, list[FileRecord]]
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    events: dict[str, dict[str, Any]] = {}
    schools: dict[str, dict[str, Any]] = {}
    for family in ("drafts_national", "drafts_rookie", "drafts_draftguru"):
        for rec in recs.get(family, []):
            header, rows = _csv_rows(rec)
            imp = q = 0
            for i, cells in enumerate(rows, start=1):
                d = dict(zip(header, cells, strict=False))
                year = _int(d.get("year"))
                pick = _int(d.get("pick"))
                name = (d.get("player_name") or "").strip()
                if year is None or not name or len(cells) != len(header):
                    state.quarantine.add("draft_events", "malformed_value", d, rec, i, season=year)
                    q += 1
                    continue
                if family == "drafts_rookie":
                    event_type = f"rookie_{(d.get('draft_type') or 'unknown').strip() or 'unknown'}"
                    rnd = None
                else:
                    event_type, rnd = "national", _int(d.get("round"))
                club_name = d.get("club") if family != "drafts_draftguru" else None
                club_id = _draft_club(state, club_name or "", year, rec) if club_name else None
                eid = f"draft:{family}:{year}:{event_type}:{pick if pick is not None else 'x'}:{_h(name, n=8)}"
                if eid in events:
                    state.quarantine.add("draft_events", "duplicate_draft_event", d, rec, i, season=year)
                    q += 1
                    continue
                events[eid] = {
                    "draft_event_id": eid,
                    "season": year,
                    "event_type": event_type,
                    "draft_round": rnd,
                    "pick": pick,
                    "club_id": club_id,
                    "club_source_name": club_name or None,
                    "player_name": name,
                    "player_id": _resolve_name(state, name, season_=None, first_season_window=(year, year + 6)),
                    "recruited_from": (d.get("recruited_from") or d.get("original_club") or "").strip() or None,
                    "grade": (d.get("grade") or "").strip() or None,
                    "source_family": family,
                    **_src(rec, i),
                }
                imp += 1
            rec.count(len(rows), imp, q)
    for rec in recs.get("draft_schools", []):
        header, rows = _csv_rows(rec)
        imp = q = 0
        for i, cells in enumerate(rows, start=1):
            d = dict(zip(header, cells, strict=False))
            name = (d.get("player_name") or "").strip()
            year = _int(d.get("year"))
            if not name or len(cells) != len(header):
                state.quarantine.add("school_observations", "malformed_value", d, rec, i, season=year)
                q += 1
                continue
            oid = f"school:{_h(rec.path, i, n=16)}"
            schools[oid] = {
                "observation_id": oid,
                "draft_year": year,
                "pick": _int(d.get("pick")),
                "player_name": name,
                "player_id": _resolve_name(state, name, season_=None, first_season_window=(year, year + 6))
                if year is not None
                else None,
                "source_wording": (d.get("original_club") or "").strip() or None,
                "school": (d.get("extracted_school") or "").strip() or None,
                "school_type": (d.get("school_type") or "").strip() or None,
                "classifier_version": "legacy",
                "confidence": "legacy_unknown",
                **_src(rec, i),
            }
            imp += 1
        rec.count(len(rows), imp, q)
    return [events[k] for k in sorted(events)], [schools[k] for k in sorted(schools)]


def _import_contracts(state: State, records: list[FileRecord]) -> list[dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for rec in records:
        header, rows = _csv_rows(rec)
        m = re.search(r"(\d{4})", rec.path.rsplit("/", 1)[-1])
        list_season = int(m.group(1)) if m else None
        imp = q = 0
        for i, cells in enumerate(rows, start=1):
            d = dict(zip(header, cells, strict=False))
            name = (d.get("player_name") or "").strip()
            if not name or len(cells) != len(header):
                state.quarantine.add("contract_observations", "malformed_value", d, rec, i, season=list_season)
                q += 1
                continue
            notes = (d.get("notes") or "").strip()
            src_m = re.search(r"\(([^)]*)\)", notes)
            source_name = src_m.group(1).strip() if src_m else None
            fa = re.sub(r"\([^)]*\)", "", notes.split("|", 1)[0]).strip() or None
            club = _club(state, d.get("club", ""), list_season, rec) if list_season and d.get("club") else None
            oid = f"contract:{_h(rec.path, i, n=16)}"
            out[oid] = {
                "observation_id": oid,
                "player_name": name,
                "player_id": _resolve_name(state, name, season_=list_season, club=club)
                or _resolve_name(state, name, season_=(list_season - 1) if list_season else None, club=club),
                "club_id": club,
                "contract_end": _int(d.get("contract_end")),
                "fa_category": fa,
                "observed_at": None,
                "source_type": "legacy",
                "source_name": source_name,
                "position": (d.get("position") or "").strip() or None,
                "notes": notes or None,
                "confidence": "low",
                **_src(rec, i),
            }
            imp += 1
        rec.count(len(rows), imp, q)
    return [out[k] for k in sorted(out)]


def _parse_score(v: Any) -> tuple[int | None, str | None]:
    m = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", str(v or "").strip())
    if not m:
        return None, f"unparseable score {v!r}"
    g, b, p = (int(x) for x in m.groups())
    if 6 * g + b != p:
        return None, f"score arithmetic mismatch {v!r}"
    return p, None


def _import_live(state: State, recs: Mapping[str, list[FileRecord]]) -> list[dict[str, Any]]:
    out: dict[tuple[str, str], dict[str, Any]] = {}
    for rec in recs.get("live_state", []):
        fname = rec.path.rsplit("/", 1)[-1]
        try:
            payload = json.loads(rec.data)
            header = payload["header"]
            gid = str(payload["gameid"])
        except (ValueError, KeyError, TypeError) as exc:
            state.quarantine.add("live_snapshots", "malformed_payload", {"error": str(exc)}, rec, None)
            rec.disposition, rec.reason = "quarantined", "malformed live snapshot JSON"
            rec.count(1, 0, 1)
            continue
        anomalies: list[str] = []
        hs, ha = _parse_score(header.get("home_score"))
        as_, aa = _parse_score(header.get("away_score"))
        anomalies += [a for a in (ha, aa) if a]
        fetched = None
        try:
            fetched = datetime.fromisoformat(str(payload.get("fetched_at_utc")).replace("Z", "+00:00")).astimezone(UTC)
        except ValueError:
            anomalies.append("unparseable fetched_at_utc")
        yr = _int(str((payload.get("meta") or {}).get("year") or "")) or (fetched.year if fetched else None)
        home_name, away_name = header.get("home_team_full"), header.get("away_team_full")
        match_id = None
        if yr and home_name and away_name and fetched:
            h = state.clubs.resolve(home_name, yr)
            a = state.clubs.resolve(away_name, yr)
            d0 = fetched.date()
            cands = [
                m
                for m in state.matches.values()
                if m.season == yr
                and {m.home, m.away} == {h, a}
                and m.match_date is not None
                and abs((m.match_date - d0).days) <= 1
            ]
            if len(cands) == 1:
                match_id = cands[0].match_id
            else:
                anomalies.append(f"match mapping ambiguous/absent ({len(cands)} candidates)")
        phase = re.sub(r"^\d+_\d{8}_\d{4}_", "", fname[:-5])
        payload_hash = rec.sha256
        out[(gid, payload_hash)] = {
            "source_game_id": gid,
            "payload_hash": payload_hash,
            "match_id": match_id,
            "fetched_at": fetched,
            "status": header.get("status"),
            "quarter": phase,
            "home_score": hs,
            "away_score": as_,
            "schema_version": 1,
            "anomalies": json.dumps(sorted(anomalies)) if anomalies else None,
            "payload_kind": "state_json",
            "home_source_name": home_name,
            "away_source_name": away_name,
            "source_round_label": header.get("round"),
            **_src(rec, None),
        }
        rec.count(1, 1, 0)
    for rec in recs.get("live_players", []):
        fname = rec.path.rsplit("/", 1)[-1]
        gid = fname.split("_", 1)[0]
        out[(gid, rec.sha256)] = {
            "source_game_id": gid,
            "payload_hash": rec.sha256,
            "match_id": None,
            "fetched_at": None,
            "status": None,
            "quarter": None,
            "home_score": None,
            "away_score": None,
            "schema_version": 1,
            "anomalies": json.dumps(
                ["per-player FanFooty payload: colNN_unknown and misindexed goals/behinds/clangers are not facts"]
            ),
            "payload_kind": "players_csv",
            "home_source_name": None,
            "away_source_name": None,
            "source_round_label": None,
            **_src(rec, None),
        }
        rec.count(1, 1, 0)
        rec.reason = "payload archived by hash; per-player cells not imported as facts"
    return [out[k] for k in sorted(out)]


_PRED_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("next_round", re.compile(r"^next_round_(?P<round>\d+)_prediction_(?P<ts>\d{8}_\d{4})\.csv$")),
    ("next_game", re.compile(r"^next_game_round(?P<round>\d+)_predictions_(?P<ts>\d{8}_\d{4})\.csv$")),
    ("next_game", re.compile(r"^next_game_predictions_(?P<ts>\d{8}_\d{4})\.csv$")),
    ("next_round", re.compile(r"^next_round_predictions_(?P<ts>\d{8}_\d{4})\.csv$")),
    (
        "prediction_vs_actual",
        re.compile(r"^prediction_vs_actual_round_(?P<round>\d+)_(?P<season>\d{4})_(?P<ts>\d{8}_\d{4})\.csv$"),
    ),
)


def _import_predictions(state: State, records: list[FileRecord]) -> list[dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for rec in records:
        fname = rec.path.rsplit("/", 1)[-1]
        kind, m = next(((k, p.match(fname)) for k, p in _PRED_PATTERNS if p.match(fname)), (None, None))
        header, rows = _csv_rows(rec)
        if kind is None or m is None or "player" not in header or "predicted_disposals" not in header:
            rec.disposition, rec.reason = "quarantined", "unrecognized legacy prediction file"
            for i, r in enumerate(rows, start=1):
                state.quarantine.add("legacy_predictions", "unrecognized_file", {"cells": r, "header": header}, rec, i)
            rec.count(len(rows), 0, len(rows))
            continue
        gd = m.groupdict()
        claimed_season = int(gd["season"]) if gd.get("season") else None
        context_season = claimed_season or int(gd["ts"][:4])
        imp = q = 0
        for i, cells in enumerate(rows, start=1):
            d = dict(zip(header, cells, strict=False))
            name = (d.get("player") or "").strip()
            pred_raw = d.get("predicted_disposals")
            pred = _float(pred_raw)
            if not name or len(cells) != len(header) or (pred is None and (pred_raw or "").strip()):
                state.quarantine.add("legacy_predictions", "malformed_value", d, rec, i, season=claimed_season)
                q += 1
                continue
            team = (d.get("team") or "").strip() or None
            club = state.clubs.resolve(team, context_season) if team else None
            pid = _resolve_name(state, name, season_=context_season, club=club, reversed_order=True)
            rid = f"lp:{_h(rec.path, n=12)}:{i}"
            out[rid] = {
                "prediction_row_id": rid,
                "artifact_kind": kind,
                "claimed_round_label": gd.get("round"),
                "claimed_season": claimed_season,
                "claimed_timestamp": gd["ts"],
                "player_display_name": name,
                "team_source_name": team,
                "club_id": club,
                "player_id": pid,
                "predicted_value": pred,
                "claimed_actual": _float(d.get("actual_disposals")),
                "origin": Origin.LEGACY_UNKNOWN.value,
                **_src(rec, i),
            }
            imp += 1
        rec.count(len(rows), imp, q)
    return [out[k] for k in sorted(out)]


def _import_rankings(
    state: State, recs: Mapping[str, list[FileRecord]]
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    def pid_for(slug: str) -> str | None:
        try:
            pid = ids.player_id_for_slug(slug)
        except ValueError:
            return None
        return pid if pid in state.players else None

    scores: dict[str, dict[str, Any]] = {}
    for rec in recs.get("rank_scores", []):
        header, rows = _csv_rows(rec)
        imp = q = 0
        for i, cells in enumerate(rows, start=1):
            d = dict(zip(header, cells, strict=False))
            slug = (d.get("player") or "").strip()
            if not slug or slug in scores:
                state.quarantine.add(
                    "legacy_rank_scores", "malformed_value" if not slug else "duplicate_key", d, rec, i
                )
                q += 1
                continue
            pid = pid_for(slug)
            if pid is None:
                state.issues.add(
                    "rank_player_unresolved",
                    Severity.WARNING,
                    f"ranking slug {slug!r} has no player identity",
                    table="legacy_rank_scores",
                    row_key=slug,
                    source_path=rec.path,
                )
            scores[slug] = {
                "player_slug": slug,
                "player_id": pid,
                "rank": i,
                "all_time_score": _float(d.get("all_time_score")),
                **_src(rec, i),
            }
            imp += 1
        rec.count(len(rows), imp, q)
    yearly: dict[tuple[int, str], dict[str, Any]] = {}
    for rec in recs.get("rank_yearly", []):
        yr = int(re.findall(r"\d{4}", rec.path)[-1])
        header, rows = _csv_rows(rec)
        imp = q = 0
        for i, cells in enumerate(rows, start=1):
            d = dict(zip(header, cells, strict=False))
            slug = (d.get("player") or "").strip()
            if not slug or (yr, slug) in yearly:
                state.quarantine.add(
                    "legacy_rank_yearly", "malformed_value" if not slug else "duplicate_key", d, rec, i, season=yr
                )
                q += 1
                continue
            yearly[(yr, slug)] = {
                "season": yr,
                "player_slug": slug,
                "player_id": pid_for(slug),
                "rank": i,
                "score": _float(d.get("score")),
                "percentile_rank": _float(d.get("percentile_rank")),
                "games_played": _int(d.get("games_played")),
                **_src(rec, i),
            }
            imp += 1
        rec.count(len(rows), imp, q)
    bios: dict[int, dict[str, Any]] = {}
    for rec in recs.get("top100_bios", []):
        header, rows = _csv_rows(rec)
        imp = q = 0
        for i, cells in enumerate(rows, start=1):
            d = dict(zip(header, cells, strict=False))
            serial = _int(d.get("Serial Number"))
            if serial is None or serial in bios or not (d.get("Player Name") or "").strip():
                state.quarantine.add("legacy_top100_bios", "malformed_value", d, rec, i)
                q += 1
                continue
            bios[serial] = {
                "serial_number": serial,
                "player_name": d["Player Name"].strip(),
                "footy_teams": d.get("Footy Teams") or None,
                "comment": d.get("Comment") or None,
                **_src(rec, i),
            }
            imp += 1
        rec.count(len(rows), imp, q)
    return (
        [scores[k] for k in sorted(scores)],
        [yearly[k] for k in sorted(yearly)],
        [bios[k] for k in sorted(bios)],
    )


# ---------------------------------------------------------------------------
# Table assembly
# ---------------------------------------------------------------------------


def _to_table(name: str, rows: list[dict[str, Any]]) -> Any:
    import pyarrow as pa

    schema = TABLES[name].arrow_schema()
    cols = {f.name: [r.get(f.name) for r in rows] for f in schema}
    table = pa.Table.from_pydict(cols, schema=schema)
    return table.sort_by([(k, "ascending") for k in TABLES[name].key])


def _sorted(table: Any, name: str) -> Any:
    return table.sort_by([(k, "ascending") for k in TABLES[name].key])


def import_legacy(
    source_root: Path,
    context: RunContext,
    *,
    config_dir: Path | None = None,
) -> DatasetCandidate:
    """Import the legacy corpus under ``source_root`` into a new snapshot candidate.

    ``config_dir`` defaults to the package repository ``config/`` (team/venue aliases).
    Never mutates ``source_root``. Returns an unpromoted candidate; validate then promote.
    """
    timings: dict[str, float] = {}
    t0 = time.perf_counter()
    mark = t0

    def tick(label: str) -> None:
        nonlocal mark
        now = time.perf_counter()
        timings[label] = round(now - mark, 3)
        mark = now

    cfg = config_dir or REPO_CONFIG_DIR
    try:
        clubs = ids.ClubRegistry.from_csv(cfg / "team_aliases.csv")
        venues = ids.VenueRegistry.from_csv(cfg / "venue_aliases.csv")
    except (OSError, KeyError, ValueError) as exc:
        raise LegacyImportError(f"invalid identity config in {cfg}: {exc}") from exc
    state = State(clubs=clubs, venues=venues)

    records = _inventory(source_root)
    by_family: dict[str, list[FileRecord]] = defaultdict(list)
    for r in records:
        by_family[r.family].append(r)
    missing = [f for f, mandatory in FAMILIES.items() if mandatory and not by_family.get(f)]
    if missing:
        raise LegacyImportError(f"mandatory legacy families missing under {source_root}: {missing}")
    tick("inventory")

    for fam, reason in IGNORED_REASONS.items():
        for r in by_family.get(fam, []):
            r.disposition, r.reason = "ignored", reason
    for r in by_family.get("unknown", []):
        r.disposition, r.reason = "quarantined", "unrecognized file family; preserved by path/hash"
        state.issues.add(
            "unknown_file_family",
            Severity.WARNING,
            f"unrecognized legacy file {r.path}",
            table="source_files",
            row_key=r.path,
            source_path=r.path,
        )

    match_rows = _import_matches(state, by_family["matches"], opponent_evidence(by_family["player_performance"]))
    tick("matches")
    evidence = _load_evidence({r.path: r for r in by_family.get("identity_evidence", [])})
    player_rows, alias_rows = _import_players(
        state, by_family["player_performance"], by_family.get("player_personal", []), evidence
    )
    tick("players")
    pg_table = _import_player_games(state, by_family["player_performance"])
    for r in (*by_family["player_performance"], *by_family.get("player_personal", [])):
        r.data = b""  # release ~170 MB of raw bytes once parsed
    tick("player_games")
    lineup_table = _import_lineups(state, by_family.get("lineups", []))
    tick("lineups")
    drafts, schools = _import_drafts(state, by_family)
    contracts = _import_contracts(state, by_family.get("contracts", []))
    live = _import_live(state, by_family)
    preds = _import_predictions(state, by_family.get("legacy_predictions", []))
    rank_scores, rank_yearly, bios = _import_rankings(state, by_family)
    tick("other_families")

    # seasons
    seasons: dict[int, dict[str, Any]] = {}
    for m in match_rows:
        s = seasons.setdefault(
            m["season"],
            {
                "season": m["season"],
                "first_match_date": None,
                "last_match_date": None,
                "matches_complete": 0,
                "matches_scheduled": 0,
                "fixture_checked_at": None,
                "schedule_complete": None,
                "source_status": None,
            },
        )
        d = m["match_date"]
        if d is not None:
            s["first_match_date"] = min(filter(None, [s["first_match_date"], d]))
            s["last_match_date"] = max(filter(None, [s["last_match_date"], d]))
        s["matches_complete"] += m["status"] == MatchStatus.COMPLETE.value
        s["matches_scheduled"] += m["status"] == MatchStatus.SCHEDULED.value

    venue_rows = venues.venue_rows(state.accounting.get("venues_observed", {}))
    source_file_rows = [r.as_report() for r in records]

    builder = SnapshotBuilder(context.data_root, clock=context.clock, code_version=IMPORTER_VERSION, run_id=None)
    tables: dict[str, Any] = {
        "players": _to_table("players", player_rows),
        "player_aliases": _to_table("player_aliases", alias_rows),
        "clubs": _to_table("clubs", clubs.club_rows()),
        "club_aliases": _to_table("club_aliases", clubs.alias_rows()),
        "venues": _to_table("venues", venue_rows),
        "seasons": _to_table("seasons", [seasons[k] for k in sorted(seasons)]),
        "matches": _to_table("matches", match_rows),
        "player_games": _sorted(pg_table, "player_games"),
        "lineups": _sorted(lineup_table, "lineups"),
        "draft_events": _to_table("draft_events", drafts),
        "school_observations": _to_table("school_observations", schools),
        "contract_observations": _to_table("contract_observations", contracts),
        "live_snapshots": _to_table("live_snapshots", live),
        "legacy_predictions": _to_table("legacy_predictions", preds),
        "legacy_rank_scores": _to_table("legacy_rank_scores", rank_scores),
        "legacy_rank_yearly": _to_table("legacy_rank_yearly", rank_yearly),
        "legacy_top100_bios": _to_table("legacy_top100_bios", bios),
        "quarantine": _to_table("quarantine", list(state.quarantine.rows.values())),
        "quality_issues": _to_table("quality_issues", list(state.issues.rows.values())),
        "source_files": _to_table("source_files", source_file_rows),
    }
    tick("assemble")
    for name, table in tables.items():
        part = TABLES[name].partition_by
        if part and table.num_rows:
            builder.add_partitioned(name, table, part)
        else:
            builder.add(name, table)
    severity_counts = Counter(i["severity"] for i in state.issues.rows.values())
    aggregate = hashlib.sha256("".join(f"{r.path}\0{r.sha256}\n" for r in records).encode()).hexdigest()
    cand = builder.finish(
        status=DatasetStatus.LEGACY_UNVERIFIED,
        source_revisions={"legacy_input_aggregate_sha256": aggregate, "importer": IMPORTER_VERSION},
        quality={k: severity_counts[k] for k in sorted(severity_counts)},
        notes=("legacy import: available_at unknown; dates labelled by date_quality",),
    )
    tick("write_snapshot")

    families: dict[str, dict[str, Any]] = {}
    for fam in FAMILIES:
        rs = by_family.get(fam, [])
        families[fam] = {
            "status": "present" if rs else "absent",
            "files": len(rs),
            "rows_read": sum(r.rows_read or 0 for r in rs),
            "rows_imported": sum(r.rows_imported or 0 for r in rs),
            "rows_quarantined": sum(r.rows_quarantined or 0 for r in rs),
            "dispositions": dict(sorted(Counter(r.disposition for r in rs).items())),
        }
    matches_acc = families["matches"]
    report: dict[str, Any] = {
        "schema_version": 1,
        "importer": IMPORTER_VERSION,
        "snapshot_id": cand.manifest.snapshot_id,
        "status": DatasetStatus.LEGACY_UNVERIFIED.value,
        "source_root": str(source_root),
        "input_aggregate_sha256": aggregate,
        "files": source_file_rows,
        "families": families,
        "tables": {k: v.num_rows for k, v in tables.items()},
        "row_accounting": {
            "matches": {
                "read": matches_acc["rows_read"],
                "imported": matches_acc["rows_imported"],
                "quarantined": matches_acc["rows_quarantined"],
            },
            "player_games": state.accounting["player_games"],
            "lineups": state.accounting.get("lineups", {}),
        },
        "quality_issue_counts": dict(sorted(Counter(i["rule_id"] for i in state.issues.rows.values()).items())),
        "quality_severity_counts": dict(sorted(severity_counts.items())),
        "quarantine_counts": dict(
            sorted(Counter(f"{q['table_name']}:{q['reason']}" for q in state.quarantine.rows.values()).items())
        ),
        "identity": {
            "duplicates": [
                {
                    "duplicate": ids.player_id_for_slug(d.duplicate_slug),
                    "canonical": ids.player_id_for_slug(d.canonical_slug),
                    "source": d.source_url,
                }
                for d in ids.KNOWN_DUPLICATES
            ],
            "verified_source_aliases": len(ids.VERIFIED_SOURCE_ALIASES),
            "players_with_source_urls": sum(1 for p in player_rows if p["source_urls"]),
            "clubs_auto_created": dict(sorted(clubs.created.items())),
        },
        "timings_s": timings,
        "wall_s": round(time.perf_counter() - t0, 3),
    }
    return DatasetCandidate(candidate=cand, report=report, data_root=context.data_root)


def iter_family_paths(report: Mapping[str, Any], family: str) -> Iterable[str]:
    return (f["path"] for f in report["files"] if f["family"] == family)


_ = (StageType, Callable, timedelta)  # re-exported types used in annotations elsewhere
